from pathlib import Path

path = Path('character.html')
src = path.read_text(encoding='utf-8')
old = """      // Preserve only pending local changes newer than the exact cloud baseline.\n      // sync.js stores raw localStorage values + timestamps in this journal.\n      let pendingApplied = 0;\n      try {\n        const rawJournal = localStorage.getItem(dirtyPrefix + domain);\n        const journal = rawJournal ? JSON.parse(rawJournal) : null;\n        const items = journal && journal.items && typeof journal.items === 'object' ? journal.items : {};\n        Object.entries(items).forEach(([k, item]) => {\n          if(!localBelongsTo(domain, k) || !item || (item.ts || 0) <= remoteMs) return;\n          if(item.removed) delete state[k];\n          else state[k] = parseRaw(item.value);\n          pendingApplied++;\n        });\n      } catch(e) {}\n\n      dump.domains[domain] = {\n        cloudUpdatedAt: row.updated_at || null,\n        cloudRestoreGeneration: Math.max(0, Math.floor(Number(row.restore_generation) || 0)),\n        pendingLocalApplied: pendingApplied,\n        data: state\n      };\n"""
new = """      // Preserve only pending local changes from the exact cloud generation and\n      // newer than that cloud baseline. Legacy journal entries intentionally map\n      // to generation 0; after the first restore generation bump they can no\n      // longer leak pre-restore device state into a fresh backup.\n      const remoteGeneration = Math.max(0, Math.floor(Number(row.restore_generation) || 0));\n      let pendingApplied = 0;\n      try {\n        const rawJournal = localStorage.getItem(dirtyPrefix + domain);\n        const journal = rawJournal ? JSON.parse(rawJournal) : null;\n        const items = journal && journal.items && typeof journal.items === 'object' ? journal.items : {};\n        Object.entries(items).forEach(([k, item]) => {\n          if(!localBelongsTo(domain, k) || !item) return;\n          const itemGeneration = Math.max(0, Math.floor(Number(item.generation) || 0));\n          if(itemGeneration !== remoteGeneration || (item.ts || 0) <= remoteMs) return;\n          if(item.removed) delete state[k];\n          else state[k] = parseRaw(item.value);\n          pendingApplied++;\n        });\n      } catch(e) {}\n\n      dump.domains[domain] = {\n        cloudUpdatedAt: row.updated_at || null,\n        cloudRestoreGeneration: remoteGeneration,\n        pendingLocalApplied: pendingApplied,\n        data: state\n      };\n"""
count = src.count(old)
if count != 1:
    raise SystemExit(f'expected exactly one backup dirty-overlay block, found {count}')
path.write_text(src.replace(old, new), encoding='utf-8')
print('Patched Character backup dirty overlay to require exact restore generation.')
