/* ChatGPT · isolated Home design experiment. All state is synthetic and memory-only. */
(function(){
  'use strict';
  const M=[
    ['budgeting','Budgeting','budgeting',3,false],['sleep','Sleep','sleep',3,false],['nutrition','Nutrition','nutrition',5,true],
    ['walking','Stappen','steps',4,true],['teeth','Brush Teeth','teeth',5,true],['household','Opgeruimd','household',4,true],
    ['meditation','Meditatie','meditation',3,false],['gratitude','Gratitude','gratitude',4,false],['good_deed','Goede daad','good-deed',3,false],
    ['screen_time','Screen Time','screen-time',4,false],['cold_shower','Cold Shower','cold-shower',2,false]
  ];
  function createDemo(){return {missions:M.map(m=>({key:m[0],name:m[1],dir:m[2],level:m[3],done:m[4]})),completionOrder:[],featuredKey:'meditation',tennisMoved:false,practice:false,words:[]};}
  function orderedMissions(state){const recent=state.completionOrder.map(key=>state.missions.find(m=>m.key===key)).filter(m=>m&&m.done);return recent.concat(state.missions.filter(m=>!recent.includes(m)));}
  function toggleMission(state,key){const m=state.missions.find(x=>x.key===key);if(!m)return null;m.done=!m.done;state.completionOrder=state.completionOrder.filter(k=>k!==key);if(m.done){state.completionOrder.unshift(key);state.featuredKey=key;}else if(state.featuredKey===key){state.featuredKey=state.completionOrder[0]||key;}return m;}
  function advanceFeatured(state,delta){const i=state.missions.findIndex(m=>m.key===state.featuredKey);state.featuredKey=state.missions[(i+delta+state.missions.length)%state.missions.length].key;return state.featuredKey;}
  if(typeof module==='object'&&module.exports){module.exports={createDemo,toggleMission,orderedMissions,advanceFeatured};return;}
  let state=createDemo(),toastTimer,activePanel='',selectedMission='';
  const $=id=>document.getElementById(id),dialog=$('detailDialog'),content=$('detailContent');
  const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
  let rotationPaused=motionPreference.matches,heroVisible=true;
  const hero=$('missionHero');
  const missionCopy={budgeting:'Even overzicht in je geld.',sleep:'Rust hoort ook bij vooruitgang.',nutrition:'Goed eten, goed voor jezelf zorgen.',walking:'Stap voor stap je hoofd leeg.',teeth:'Een kleine gewoonte, elke dag.',household:'Een beetje ruimte in je huis én hoofd.',meditation:'Even landen. Dan weer verder.',gratitude:'Bewaar iets dat vandaag goed was.',good_deed:'Maak iemands dag een beetje beter.',screen_time:'Meer ruimte voor het leven buiten je scherm.',cold_shower:'Jouw bestaande missie; samen nog te reviewen.'};
  function renderFeatured(){const m=state.missions.find(m=>m.key===state.featuredKey);const latest=state.completionOrder[0]===m.key;$('heroTitle').textContent=m.name;$('featuredCopy').textContent=missionCopy[m.key];$('featuredEyebrow').textContent=latest?'NET AFGEVINKT · DEMO':'JE DAILY MISSIONS';$('heroImage').src=image(m);$('heroImage').alt=m.name+' companion, bestaande beeldreferentie';$('heroImageButton').setAttribute('aria-label','Open missie-overzicht, uitgelicht: '+m.name);$('featuredStatus').textContent=(m.done?'Gedaan ✓':'Nog te doen')+' · demo L'+m.level;$('rotationToggle').textContent=rotationPaused?'Start wisselen':'Pauzeer wisselen';$('rotationToggle').setAttribute('aria-pressed',String(!rotationPaused));$('featuredPosition').textContent=(state.missions.indexOf(m)+1)+' / '+state.missions.length;}
  function renderCrew(){const recent=orderedMissions(state).filter(m=>state.completionOrder.includes(m.key));const fallback=['walking','meditation','household'].map(key=>state.missions.find(m=>m.key===key));const crew=recent.concat(fallback.filter(m=>!recent.includes(m))).slice(0,3);$('crewPreview').innerHTML=crew.map(m=>'<button type="button" data-mission="'+m.key+'"><img src="'+image(m)+'" alt=""><span>'+m.name+'</span><small>'+(m.done?'Gedaan ✓':'Nog te doen')+'</small></button>').join('');}
  function image(m){return 'img/lab/park31/'+m.dir+'/l'+String(m.level).padStart(2,'0')+'.webp';}
  function note(text){return '<p class="info-note">'+text+'</p>';}
  function toast(text){$('demoToast').textContent=text;$('demoToast').classList.add('show');if($('sheetStatus'))$('sheetStatus').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('demoToast').classList.remove('show'),3000);}
  function update(){const count=state.missions.filter(m=>m.done).length;$('dayCount').textContent=count;$('dayFill').style.width=count/state.missions.length*100+'%';renderFeatured();renderCrew();$('nextTime').textContent=state.tennisMoved?'20:00':'19:00';$('nextEvent').textContent=state.tennisMoved?'Afspreken met vrienden':'Tennis met een vriend';}
  function sheet(title,html){$('detailTitle').textContent=title;content.innerHTML=html;const status=document.createElement('p');status.id='sheetStatus';status.setAttribute('role','status');content.append(status);if(!dialog.open)dialog.showModal();}
  function missionDetail(key){const m=state.missions.find(m=>m.key===key);if(!m)return;activePanel='mission';selectedMission=key;sheet(m.name,'<div class="detail-art"><img src="'+image(m)+'" alt="'+m.name+' companion"><div><h3>Level '+m.level+'</h3><p>Voorbeeldlevel · bestaande art.<br>Huidige status: '+(m.done?'gedaan':'nog te doen')+'.</p></div></div><button class="action" data-toggle-mission="'+key+'">'+(m.done?'Demo-vinkje terugnemen':'Probeer afvinken ✓')+'</button> <button class="action secondary" data-open="missions">Alle missies</button>'+note('Dit verandert alleen het voorbeeldvinkje in deze proef. Je echte levels, XP en missieregels worden niet aangepast. Transparantie en nieuwe beweging blijven apart werk.'));}
  function open(panel){activePanel=panel;
    if(panel==='missions'){sheet('Jouw Daily Missions','<p>Vink af met het rondje; tik op een companion voor details. Je laatste voltooiing komt vooraan.</p><div class="mission-rail" aria-label="Alle missies, laatste voltooiing eerst">'+orderedMissions(state).map(m=>'<button type="button" data-mission="'+m.key+'"><img src="'+image(m)+'" alt=""><span>'+m.name+'</span></button>').join('')+'</div><div class="mission-grid">'+orderedMissions(state).map(m=>'<div class="mission-card" data-done="'+m.done+'"><button class="mission-option" type="button" data-mission="'+m.key+'"><img src="'+image(m)+'" alt=""><strong>'+m.name+'</strong><span>'+(m.done?'Gedaan ✓':'Nog te doen')+' · demo L'+m.level+'</span></button><button type="button" class="mission-check" data-toggle-mission="'+m.key+'" aria-label="'+m.name+': demo voltooid" aria-pressed="'+m.done+'">'+(m.done?'✓':'+')+'</button></div>').join('')+'</div>'+note('Alle 11 huidige openbare missies zijn opgenomen. Ook Sleep en Cold Shower blijven staan tot we de review samen doen. Privé-missies tonen we niet in deze voorbeeldgegevens.'));}
    else if(panel==='agenda'){sheet('Ruimte voor je dag','<p>Voorbeeldagenda · tik om het idee van flexibel plannen te testen.</p><div class="row"><span class="stamp">'+(state.tennisMoved?'Morgen':'19:00')+'</span><div><strong>Tennis met een vriend</strong><small>'+(state.tennisMoved?'19:00 · verplaatst, niet mislukt':'60 minuten · bewegen + sociaal')+'</small></div><button class="action secondary" id="moveTennis">'+(state.tennisMoved?'Zet terug':'Schuif naar morgen')+'</button></div><div class="row"><span class="stamp">20:00</span><div><strong>Afspreken met vrienden</strong><small>Een sociaal moment · voorbeeld</small></div></div>'+note('Eén agenda voor afspraken en geplande taken. De echte agenda blijft waar hij is. Deze proef past geen afspraken aan.'));}
    else if(panel==='week'){sheet('Een week die goed voelt','<p>Ritme boven een perfecte checklist. Dit is jouw afgesproken richting met voorbeeldtellers.</p><div class="week-stat"><span>Sport of bewegen<small> · voorbeeld</small></span><b>2 / 3</b></div><div class="week-stat"><span>Sociale momenten</span><b>1 / 2–3</b></div><div class="week-stat"><span>Dagelijkse stappen</span><b>10.000</b></div><div class="path-step"><b>Weekend: iets om naar uit te kijken</b><small>Voorbeeld: een wandeling met iemand. Mag tegelijk meetellen als bewegen én sociaal moment.</small></div><button class="action" data-open="agenda">Schuif een gepland moment</button>'+note('De nieuwe weekmissies zijn nog niet in de echte app geïmplementeerd. Je bestaande Weekly Win en Monthly Boss blijven behouden en staan onder Overzicht.'));}
    else if(panel==='path'){sheet('Eén skill. Een volgende stap.','<div class="path-step"><b>WHY · Blijheid & verbinding</b><small>Voorbeeldkoppeling: plezier in tennis en samen bewegen. Dit is nog geen opgeslagen koppeling met je echte doelen.</small></div><div class="path-step"><b>NU · Een gecontroleerde rally</b><small>Voorstel: oefen gericht op tien ballen achter elkaar. Niveau en mijlpaal bepalen we samen, niet automatisch uit een levelnummer.</small></div><div class="path-step"><b>DAARNA · Maak groei zichtbaar</b><small>Een merkbaar beloningsmoment en evolutie zodra een afgesproken mijlpaal gehaald is.</small></div><button class="action" id="practiceButton">'+(state.practice?'Voorbeeldbeloning opnieuw tonen':'Probeer een beloningsmoment ✦')+'</button>'+note('Dit laat de structuur zien: waarom → oefenen → mijlpaal → beloning. Het vervangt nog geen skill, Season, beoordeling of doelenpad.'));}
    else if(panel==='gratitude'){sheet('Wat was een goed moment?','<p>Een klein moment bewaren, zonder een groot formulier.</p><form class="grat-form" id="demoGratForm"><input id="demoGratInput" aria-label="Een goed moment in deze demo" placeholder="Bijvoorbeeld: lachen na tennis" maxlength="60"><button class="action" type="submit">Bewaar</button></form><div class="grat-chips" id="demoGratChips"></div>'+note('Alleen zolang deze proef openstaat. Niet opgeslagen in je echte Gratitude.'));renderWords();}
    else if(panel==='why'){sheet('Waar doe je het voor?','<h3>Je wilt kunnen denken: ik heb iets gedaan.</h3><p>Bewogen, mensen gezien, je huis op orde. Vandaag draagt bij aan de week die jij fijn vindt.</p><div class="path-step"><b>Je grotere richting blijft de basis</b><small>Liefde · Geld · Vrijheid · Blijheid · Exploration. Het bestaande honderdjarenplan blijft behouden.</small></div>'+note('Dit is een ontwerp voor een korte WHY op Home. Concrete doelkoppelingen moeten nog worden gecontroleerd; de WHY-link blijft open.')+'<button class="action" data-open="path">Bekijk het voorbeeldpad</button>');}
    else if(panel==='phone'){sheet('Home op telefoonformaat','<iframe title="Home-proef op telefoonformaat" src="lab-home-v2.html" style="display:block;width:390px;max-width:100%;height:650px;margin:auto;border:1px solid var(--line);border-radius:20px"></iframe>');}
    else if(panel==='more'){const items=[['agenda','Agenda & taken','Plannen en je to-do’s'],['missions','Daily Missions','Alle bestaande missies'],['week','Weekritme','Bewegen, samen, weekend'],['path','Skills & Seasons','Oefenen, mijlpalen en assessment'],['why','Doelen & WHY','Richting en honderdjarenplan'],['health','Body & Health','Fitbit, herstel, water en training'],['quests','Quests & historie','Weekly Win en Monthly Boss'],['finance','Finance & Ventures','Geld, projecten en volgende acties'],['explore','Routes & recepten','Op pad en praktisch'],['gratitude','Gratitude','Je goede momenten'],['jarvis','Jarvis & Lab','Hulp, experimenten en HQ'],['settings','Instellingen','Account en voorkeuren']];sheet('Alles heeft een plek','<p>Een voorstel voor de ingang naar de bestaande onderdelen. Geen functies verwijderd.</p><div class="app-grid">'+items.map(i=>'<button type="button" data-open="'+i[0]+'"><strong>'+i[1]+'</strong><small>'+i[2]+'</small></button>').join('')+'</div>');}
    else if(panel==='review'){sheet('De keuzes achter deze proef','<p>De huidige Home stapelt veel volledige onderdelen. In deze proef zie je eerst de kern; details openen pas op verzoek.</p><table class="review-map"><thead><tr><th>Huidige onderdelen</th><th>Voorstel</th></tr></thead><tbody><tr><td>Groet, quote, karakter, Daily Level</td><td>Eén visueel dagblok. Een quote hoeft niet steeds eigen ruimte te nemen.</td></tr><tr><td>Agenda, My To-Do, Next Move</td><td>Compacte agenda + één volgende actie. Taken bereikbaar in Overzicht.</td></tr><tr><td>Volledige mission-roster</td><td>Een kleine crew + alle missies op tikafstand. Geen missies schrappen.</td></tr><tr><td>Season, WHY, challenge, skills</td><td>Eén actueel groeipad; de rest blijft bereikbaar.</td></tr><tr><td>Quests, Health, Finance, tools</td><td>Eigen plek in Overzicht; context op Home wanneer relevant.</td></tr></tbody></table><h3>Drie gerichte keuzes</h3>'+question('hero','1. Hoe groot mag je karakter op Home zijn?',['Zoals nu','Groter, meer wereld','Kleiner, meer overzicht'])+question('first','2. Wat wil je direct onder het karakter?',['Agenda + weekritme','Daily Missions eerst'])+question('color','3. Welke kleurstand voelt meer als jouw app?',['Nacht met kleur','Licht met kleur'])+'<p><button class="action" id="copyReview">Kopieer mijn feedback</button></p><textarea id="reviewOutput" aria-label="Kopieerbare feedback" rows="4" readonly placeholder="Kies hierboven; je feedback verschijnt hier."></textarea>'+note('Jouw keuzes zijn alleen in dit venster aanwezig. Stuur ze in de chat; er wordt niets automatisch ingevoerd of goedgekeurd.'));}
    else{const rest={health:['Body & Health','Fitbit-status, herstel, training, water, gewicht en workout challenges houden hun eigen plek. Deze Home-proef haalt geen gezondheidsdata op en repareert Fitbit niet.'],quests:['Quests & historie','Je bestaande week- en maandquests, historie en beloningen blijven behouden. Nieuw weekritme komt ernaast na onze review.'],finance:['Finance & Ventures','Finance houdt schulden, budget en portfolio. Ventures houdt zijn eigen werkplek. Alleen de relevante volgende actie hoeft naar Home.'],explore:['Routes & recepten','Routes, wandelplannen en recepten blijven bereikbaar. Een weekendplan kan later vanuit Routes op je weekblok verschijnen.'],jarvis:['Jarvis & Lab','Jarvis blijft je assistent. ChatGPT Lab, Claude Lab, Operation Hub en HQ behouden hun eigen functie. Open feedback blijft staan.'],settings:['Instellingen','Account, privacy en voorkeuren blijven bij Instellingen. Deze proef maakt geen wijzigingen aan je account.']};const entry=rest[panel];if(entry)sheet(entry[0],'<p>'+entry[1]+'</p>'+note('Dit onderdeel is alleen ingedeeld in het ontwerp, niet opnieuw gebouwd.')+'<button class="action secondary" data-open="more">Terug naar overzicht</button>');}
  }
  function question(name,title,options){return '<div class="review-question"><fieldset><legend>'+title+'</legend>'+options.map(x=>'<label><input type="radio" name="'+name+'" value="'+x+'">'+x+'</label>').join('')+'</fieldset></div>';}
  function renderWords(){const box=$('demoGratChips');if(!box)return;box.textContent='';for(const word of state.words){const span=document.createElement('span');span.textContent=word;box.append(span);}}
  document.addEventListener('click',async function(e){const target=e.target.closest('button,[data-open]');if(!target)return;
    if(target.dataset.open){open(target.dataset.open);return;}if(target.dataset.mission){missionDetail(target.dataset.mission);return;}
    if(target.dataset.themeChoice){document.body.dataset.theme=target.dataset.themeChoice;document.querySelectorAll('[data-theme-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b===target)));return;}
    if(target.dataset.featureStep){advanceFeatured(state,Number(target.dataset.featureStep));rotationPaused=true;renderFeatured();return;}
    if(target.id==='rotationToggle'){rotationPaused=!rotationPaused;renderFeatured();return;}
    if(target.dataset.toggleMission){const fromOverview=activePanel==='missions',key=target.dataset.toggleMission;const m=toggleMission(state,key);rotationPaused=true;update();if(fromOverview){open('missions');content.querySelector('[data-toggle-mission="'+key+'"]').focus();}else{missionDetail(m.key);content.querySelector('[data-toggle-mission="'+key+'"]').focus();}toast(m.done?'✦ '+m.name+' staat nu vooraan op Home. · demo':'Demo-vinkje teruggenomen');return;}
    if(target.id==='closeDetail'){dialog.close();return;}if(target.id==='todayButton'){window.scrollTo({top:0,behavior:'smooth'});return;}
    if(target.id==='moveTennis'){state.tennisMoved=!state.tennisMoved;update();open('agenda');toast(state.tennisMoved?'Verplaatst, niet mislukt. · demo':'Tennis staat terug in de voorbeeldagenda.');return;}
    if(target.id==='practiceButton'){state.practice=true;sheet('Daar mag je even bij stilstaan.','<div class="path-step"><b>✦ Stap gezet!</b><small>Je hebt je voorbeeldtraining afgerond. Hier kan straks een karakterreactie of evolutiemoment komen.</small></div><p>Voorbeeldbeloning · geen echte XP, badge of level toegekend.</p><button class="action" data-open="path">Terug naar je pad</button>');return;}
    if(target.id==='resetDemo'){state=createDemo();rotationPaused=motionPreference.matches;update();toast('Voorbeeld gereset. Je echte gegevens zijn niet aangeraakt.');return;}
    if(target.id==='copyReview'){const fields=[['hero','Karakter'],['first','Volgorde'],['color','Kleur']];const text='Gamenfy 2.0 Home-proef\n'+fields.map(([key,label])=>label+': '+(content.querySelector('input[name="'+key+'"]:checked')?.value||'nog open')).join('\n');$('reviewOutput').value=text;try{await navigator.clipboard.writeText(text);toast('Gekopieerd. Plak je feedback in de chat.');}catch(err){$('reviewOutput').focus();$('reviewOutput').select();toast('Selecteer en kopieer de tekst hieronder.');}}
  });
  document.addEventListener('submit',function(e){if(e.target.id!=='demoGratForm')return;e.preventDefault();const input=$('demoGratInput'),text=input.value.trim();if(!text)return;state.words.push(text);input.value='';renderWords();toast('Goed moment toegevoegd aan de demo.');});
  update();
  // Only the illustrated mission changes; no character-animation or real-state engine.
  if('IntersectionObserver' in window){new IntersectionObserver(entries=>{heroVisible=entries[0].isIntersecting;}).observe(hero);}
  motionPreference.addEventListener('change',event=>{if(event.matches){rotationPaused=true;renderFeatured();}});
  setInterval(()=>{if(rotationPaused||document.hidden||dialog.open||!heroVisible||hero.matches(':hover')||hero.contains(document.activeElement))return;advanceFeatured(state,1);renderFeatured();},8000);
})();
