// =============================================================
// Gamenfy — Tiered skill ladders (v10.17)
// Unified quest + unlock path. TIER = LEVEL: claiming a tier
// brings the skill to that level. Each tier is an info tree:
// meaning / why / doThis / examples / next / claim (measurable).
// Piano + Puzzling are the reviewed templates; the same shape
// rolls out to every skill once approved.
// =============================================================
(function () {
  'use strict';
  window.SKILL_LADDERS = {
    piano: [
      { level: 1, title: 'First Contact',
        meaning: 'Learn the keyboard: find middle C, name the white keys (C D E F G A B), and see the octave pattern repeat. Sit with good posture — bench height so your forearms are level, relaxed wrists, curved hands.',
        why: 'Posture and hand shape are the foundation of everything — bad habits here cost months to unlearn and cause strain.',
        doThis: ['Play each white key up an octave and say its name out loud.', 'Find every C (just left of the group of 2 black keys).'],
        examples: ['Point out all the C\u2019s.', 'Recognise the 2-then-3 black-key pattern.'],
        next: 'Put 5 fingers on C-D-E-F-G.',
        claim: 'you can name any white key without looking and find middle C.' },
      { level: 2, title: 'Five-Finger Hand',
        meaning: 'Play a 5-finger pattern (C D E F G) with each hand separately, one finger per key, evenly.',
        why: 'Independent, even fingers are the core motor skill \u2014 this trains the brain to control each finger on its own.',
        doThis: ['Right hand thumb=C \u2026 pinky=G, slow, even tone, up and down.', 'Then the same with the left hand.'],
        examples: ['\u201cOde to Joy\u201d melody in C position.', '\u201cHot Cross Buns\u201d.'],
        next: 'Combine the hands slowly.',
        claim: 'you play a simple melody smoothly and evenly with one hand.' },
      { level: 4, title: 'Hands Together (simple)',
        meaning: 'Play a simple piece with both hands at once (melody in the right, held/simple bass in the left).',
        why: 'Coordinating two hands is the first big leap \u2014 your brain learns to split attention. Master each hand alone first, then combine at 50% tempo.',
        doThis: ['Learn each hand separately, then combine very slowly, counting out loud.'],
        examples: ['\u201cOde to Joy\u201d with left-hand root notes.'],
        next: 'Learn your first scale.',
        claim: 'you play one simple piece hands-together without mistakes.' },
      { level: 6, title: 'C Major Scale',
        meaning: 'C major scale, one octave, hands separately, using the thumb-under technique (fingering 1-2-3-1-2-3-4-5).',
        why: 'Scales train fingering, evenness and the thumb-cross that unlocks every key.',
        doThis: ['Slow, watch the thumb tuck under after E. Up and down.'],
        examples: ['C scale, then G scale.'],
        next: 'Scale hands together.',
        claim: 'you play the C scale one octave smoothly with correct fingering.' },
      { level: 9, title: 'Scale Together + First Real Piece',
        meaning: 'C scale two octaves hands together, and a beginner classical piece start to finish (e.g. a minuet from the Anna Magdalena Bach book).',
        why: 'Finishing a whole piece trains persistence, structure and musicality \u2014 not just technique.',
        doThis: ['Piece in 4-bar chunks; hand-by-hand; then together, slowly building up.'],
        examples: ['Petzold Minuet in G.', '\u201cF\u00fcr Elise\u201d (first theme).'],
        next: 'Learn chords.',
        claim: 'you can play one beginner piece all the way through.' },
      { level: 13, title: 'Chords & Accompaniment',
        meaning: 'Major/minor triads; I-IV-V-I in C and G; play a song with chord accompaniment (left-hand chords, right-hand melody or singing).',
        why: 'Chords let you play thousands of pop songs \u2014 this opens up \u201cjust making music\u201d.',
        doThis: ['Learn the shape of major/minor triads; practise switching C-F-G chords smoothly.'],
        examples: ['A 4-chord song (C-G-Am-F).'],
        next: 'Learn to sight-read.',
        claim: 'you can accompany a song with I-IV-V chords.' },
      { level: 17, title: 'Song Repertoire',
        meaning: 'Learn 3 full songs you enjoy, by heart (chords + melody). Build a set you can play any time.',
        why: 'Repertoire keeps it fun and cements everything — playing for real is the best practice.',
        doThis: ['Pick 3 songs you love; learn them fully; keep them polished.'],
        examples: ['A pop song, a film theme, and a short classical piece.'],
        next: 'Sight-reading.',
        claim: 'you can play 3 full songs from memory.' },
      { level: 20, title: 'Sight-Reading & Rhythm',
        meaning: 'Read simple sheet music at sight (grade 1-2) and count rhythms (quarters/eighths) correctly.',
        why: 'Sight-reading makes you independent \u2014 you can pick up any piece without a tutorial.',
        doThis: ['5 min a day sight-reading a new simple piece; count out loud.'],
        examples: ['Grade-1 pieces at sight.'],
        next: 'Hand independence + dynamics.',
        claim: 'you can read an unfamiliar grade-1/2 piece reasonably at sight.' },
      { level: 24, title: 'Two-Hand Independence',
        meaning: 'Pieces where the hands play genuinely different rhythms (a waltz: left hand oom-pah-pah, right hand a flowing melody).',
        why: 'True independence between the hands is what separates beginners from intermediates.',
        doThis: ['Practise a waltz or a broken-chord left hand under a singing right-hand melody.'],
        examples: ['A simple waltz; \u201cRiver Flows in You\u201d.'],
        next: 'Independence, dynamics & pedal.',
        claim: 'you play a piece with clearly independent hand rhythms.' },
      { level: 30, title: 'Independence, Dynamics & Pedal',
        meaning: 'Hands playing different rhythms; playing with dynamics (soft/loud); basic pedal use. An intermediate piece.',
        why: 'Musicality (dynamics, pedal) lifts it from \u201cnotes\u201d to \u201cmusic\u201d.',
        doThis: ['Practise a piece with marked dynamics; add pedal on chord changes.'],
        examples: ['Full \u201cF\u00fcr Elise\u201d; a Clementi sonatina.'],
        next: 'Polish an intermediate piece.',
        claim: 'you play an intermediate piece with dynamics and pedal.' },
      { level: 36, title: 'Phrasing & Half-Pedal',
        meaning: 'Musical phrasing (shaping lines), half-pedalling, and voicing the melody above the accompaniment.',
        why: 'This is where playing becomes expressive and personal, not mechanical.',
        doThis: ['Take a lyrical piece; shape each phrase; practise half-pedal changes.'],
        examples: ['\u201cComptine d\u2019un autre \u00e9t\u00e9\u201d (Am\u00e9lie).'],
        next: 'Intermediate repertoire.',
        claim: 'you play a lyrical piece with real phrasing and pedal control.' },
      { level: 45, title: 'Intermediate Repertoire',
        meaning: 'A full intermediate piece to performance level (e.g. a Chopin prelude or a Bach Invention). All 12 major scales fluent.',
        why: 'Real repertoire + all keys is the mark of a solid intermediate pianist.',
        doThis: ['Pick one intermediate piece and polish it fully; drill all 12 major scales.'],
        examples: ['Bach Invention No. 1; Chopin Prelude in E minor.'],
        next: 'Advanced technique.',
        claim: 'you perform one intermediate piece at level.' },
      { level: 55, title: 'Advanced Intermediate',
        meaning: 'A harder piece (a Chopin waltz or a Debussy miniature) and faster scales/arpeggios in all keys.',
        why: 'Bridges the gap to advanced repertoire.',
        doThis: ['Learn one advanced-intermediate piece; speed up scales in all 12 keys.'],
        examples: ['Chopin Waltz in A minor; Debussy \u201cArabesque\u201d.'],
        next: 'Advanced technique.',
        claim: 'you play an advanced-intermediate piece cleanly.' },
      { level: 70, title: 'Advanced Technique',
        meaning: 'Arpeggios, fast passages, a Chopin nocturne or a Bach fugue.',
        why: 'Advanced technique opens the great repertoire.',
        doThis: ['Daily arpeggio + fast-passage drills; learn one advanced piece.'],
        examples: ['Chopin Nocturne Op. 9 No. 2.'],
        next: 'Mastery.',
        claim: 'you can play an advanced piece.' },
      { level: 85, title: 'Concert Piece',
        meaning: 'A demanding concert-level piece, polished to performance standard.',
        why: 'Performance-ready advanced repertoire is the doorway to mastery.',
        doThis: ['Choose one concert piece and refine it over months to performance level.'],
        examples: ['Debussy \u201cClair de Lune\u201d; a Chopin Ballade excerpt.'],
        next: 'Mastery.',
        claim: 'you perform a concert-level piece.' },
      { level: 100, title: 'Mastery',
        meaning: 'Perform an advanced piece from memory; improvise or accompany by ear.',
        why: 'The final tier: technique + musicianship + freedom.',
        doThis: ['Perform from memory; practise playing along by ear.'],
        examples: ['Perform a full advanced piece; jam along to a song by ear.'],
        next: 'You\u2019ve reached the top \u2014 keep the fire.',
        claim: 'you perform at level and can play by ear.' },
    ],
    puzzling: [
      { level: 1, title: 'First Puzzle',
        meaning: 'Finish a small jigsaw (100-300 pieces). Core method: turn all pieces face-up, find the edge pieces, build the frame.',
        why: 'The border gives you the boundary; sorting before you start is the fundamental skill.',
        doThis: ['Flip all pieces face-up \u2192 separate edges \u2192 build the frame \u2192 fill in.'],
        examples: ['A 300-piece landscape.'],
        next: 'Sort by colour/pattern.',
        claim: 'you finish a 100-300 piece puzzle.' },
      { level: 2, title: 'Sort & Section',
        meaning: 'Finish a 500-piece puzzle by sorting into colour/pattern groups.',
        why: 'Sorting into sections turns chaos into solvable chunks.',
        doThis: ['Group by colour/distinct features \u2192 build recognisable areas \u2192 connect them.'],
        examples: ['A 500-piece image with clear colour blocks.'],
        next: 'The standard 1000.',
        claim: 'you finish a 500-piece puzzle using the sorting method.' },
      { level: 4, title: '1000 Pieces',
        meaning: 'Finish a standard 1000-piece puzzle.',
        why: 'The \u201cstandard\u201d adult puzzle \u2014 a real milestone.',
        doThis: ['Frame \u2192 colour sections \u2192 tricky uniform areas (sky/water) by piece shape.'],
        examples: ['A 1000-piece scene.'],
        next: 'Beat the clock / uniform areas.',
        claim: 'you finish a 1000-piece puzzle.' },
      { level: 6, title: 'Beat the Clock / Uniform Areas',
        meaning: 'Finish a 1000-piece puzzle under your personal best, or one with large uniform areas (sky/sea).',
        why: 'Uniform areas force you to solve by piece shape instead of image \u2014 an advanced skill.',
        doThis: ['Time yourself; or pick a puzzle with a big plain area and solve it by shape.'],
        examples: ['A mostly-sky landscape.'],
        next: '2000 pieces.',
        claim: 'you finish a uniform-area puzzle or beat your 1000 time.' },
      { level: 9, title: '2000 Pieces',
        meaning: 'Finish a 2000-piece puzzle.',
        why: 'More volume = more sorting and memory discipline.',
        doThis: ['Sort into many trays; work section by section over multiple sessions.'],
        examples: ['A 2000-piece detailed image.'],
        next: 'Hard modes.',
        claim: 'you finish a 2000-piece puzzle.' },
      { level: 14, title: 'Hard Modes',
        meaning: 'All-white/gradient puzzles, or shaped/3D puzzles.',
        why: 'With no image you solve purely on shape \u2014 the hardest puzzle thinking.',
        doThis: ['Try an \u201cimpossible\u201d white/gradient puzzle; solve by edge shape alone.'],
        examples: ['A pure-white or gradient puzzle.'],
        next: '5000 pieces / speed.',
        claim: 'you finish a white/gradient \u201cimpossible\u201d puzzle.' },
      { level: 22, title: '5000 Pieces / Speed',
        meaning: 'Finish a 5000-piece puzzle, or reach competitive speed on 1000.',
        why: 'Scale + speed is elite territory.',
        doThis: ['Commit to a 5000 over several weeks, or time-train 1000s.'],
        examples: ['A 5000-piece panorama.'],
        next: 'Master builder.',
        claim: 'you finish a 5000-piece puzzle.' },
      { level: 40, title: 'Master Builder',
        meaning: 'A 10,000+ piece puzzle, or consistent competition times.',
        why: 'Only the dedicated get here.',
        doThis: ['Take on a 10k over a long stretch, or enter a speed event.'],
        examples: ['A 10,000-piece world map.'],
        next: 'Legend.',
        claim: 'you finish a 10,000-piece puzzle.' },
      { level: 100, title: 'Puzzle Legend',
        meaning: 'Multiple 10k+ puzzles, or a podium at a speed-puzzling competition.',
        why: 'The top of the craft.',
        doThis: ['Build a collection of giant puzzles, or compete.'],
        examples: ['Podium at a speed-puzzling event.'],
        next: 'You\u2019ve mastered it.',
        claim: 'you puzzle at competition level.' },
    ],
  };

  window.OPTIONAL_QUESTS = {
    piano: [
      { lvl: 2,  title: 'Learn: Twinkle Twinkle',        desc: 'A first full melody.',              xp: 30 },
      { lvl: 4,  title: 'Learn: Ode to Joy (two hands)', desc: 'Melody + bass together.',           xp: 40 },
      { lvl: 6,  title: 'Learn: Happy Birthday',         desc: 'Play it for someone, any key.',     xp: 40 },
      { lvl: 9,  title: 'Learn: F\u00fcr Elise (theme)',    desc: 'The famous opening.',               xp: 60 },
      { lvl: 13, title: 'Learn a 4-chord pop song',      desc: 'Your choice \u2014 C-G-Am-F.',          xp: 60 },
      { lvl: 17, title: 'Learn: River Flows in You',     desc: 'Yiruma modern classic.',            xp: 80 },
      { lvl: 20, title: 'Sight-read 5 new pieces',       desc: 'Cold-read 5 grade-1/2 pieces.',     xp: 80 },
      { lvl: 24, title: 'Learn: Clocks (Coldplay)',      desc: 'Arpeggiated pop.',                  xp: 100 },
      { lvl: 30, title: 'Learn: F\u00fcr Elise (full)',     desc: 'The whole piece.',                  xp: 120 },
      { lvl: 36, title: 'Learn: Comptine (Am\u00e9lie)',    desc: 'Yann Tiersen theme.',               xp: 150 },
      { lvl: 45, title: 'Learn: a Bach Invention',       desc: 'Two-part counterpoint.',            xp: 200 },
      { lvl: 55, title: 'Learn: a Chopin Waltz',         desc: 'e.g. A minor.',                     xp: 250 },
      { lvl: 70, title: 'Learn: Nocturne Op.9 No.2',     desc: 'Chopin.',                           xp: 350 },
      { lvl: 85, title: 'Learn: Clair de Lune',          desc: 'Debussy.',                          xp: 500 },
      { lvl: 100,title: 'Learn: a Chopin Ballade',       desc: 'Concert showpiece.',                xp: 800 },
    ],
  };
})();
