// =============================================================
// Gamenfy — Tiered skill ladders (v10.17)
// Unified quest + unlock path. TIER = LEVEL: claiming a tier
// brings the skill to that level. Each tier is an info tree:
// meaning / why / doThis / examples / next / claim (measurable).
// Piano + Puzzling are the reviewed templates; the same shape
// rolls out to every skill once approved.
// =============================================================
(function () {
  'use strict';
  window.SKILL_LADDERS = {
    piano: [
      { level: 1, title: 'First Contact',
        meaning: 'Learn the keyboard: find middle C, name the white keys (C D E F G A B), and see the octave pattern repeat. Sit with good posture — bench height so your forearms are level, relaxed wrists, curved hands.',
        why: 'Posture and hand shape are the foundation of everything — bad habits here cost months to unlearn and cause strain.',
        doThis: ['Play each white key up an octave and say its name out loud.', 'Find every C (just left of the group of 2 black keys).'],
        examples: ['Point out all the C\u2019s.', 'Recognise the 2-then-3 black-key pattern.'],
        next: 'Put 5 fingers on C-D-E-F-G.',
        claim: 'you can name any white key without looking and find middle C.' },
      { level: 2, title: 'Five-Finger Hand',
        meaning: 'Play a 5-finger pattern (C D E F G) with each hand separately, one finger per key, evenly.',
        why: 'Independent, even fingers are the core motor skill \u2014 this trains the brain to control each finger on its own.',
        doThis: ['Right hand thumb=C \u2026 pinky=G, slow, even tone, up and down.', 'Then the same with the left hand.'],
        examples: ['\u201cOde to Joy\u201d melody in C position.', '\u201cHot Cross Buns\u201d.'],
        next: 'Combine the hands slowly.',
        claim: 'you play a simple melody smoothly and evenly with one hand.' },
      { level: 4, title: 'Hands Together (simple)',
        meaning: 'Play a simple piece with both hands at once (melody in the right, held/simple bass in the left).',
        why: 'Coordinating two hands is the first big leap \u2014 your brain learns to split attention. Master each hand alone first, then combine at 50% tempo.',
        doThis: ['Learn each hand separately, then combine very slowly, counting out loud.'],
        examples: ['\u201cOde to Joy\u201d with left-hand root notes.'],
        next: 'Learn your first scale.',
        claim: 'you play one simple piece hands-together without mistakes.' },
      { level: 6, title: 'C Major Scale',
        meaning: 'C major scale, one octave, hands separately, using the thumb-under technique (fingering 1-2-3-1-2-3-4-5).',
        why: 'Scales train fingering, evenness and the thumb-cross that unlocks every key.',
        doThis: ['Slow, watch the thumb tuck under after E. Up and down.'],
        examples: ['C scale, then G scale.'],
        next: 'Scale hands together.',
        claim: 'you play the C scale one octave smoothly with correct fingering.' },
      { level: 9, title: 'Scale Together + First Real Piece',
        meaning: 'C scale two octaves hands together, and a beginner classical piece start to finish (e.g. a minuet from the Anna Magdalena Bach book).',
        why: 'Finishing a whole piece trains persistence, structure and musicality \u2014 not just technique.',
        doThis: ['Piece in 4-bar chunks; hand-by-hand; then together, slowly building up.'],
        examples: ['Petzold Minuet in G.', '\u201cF\u00fcr Elise\u201d (first theme).'],
        next: 'Learn chords.',
        claim: 'you can play one beginner piece all the way through.' },
      { level: 13, title: 'Chords & Accompaniment',
        meaning: 'Major/minor triads; I-IV-V-I in C and G; play a song with chord accompaniment (left-hand chords, right-hand melody or singing).',
        why: 'Chords let you play thousands of pop songs \u2014 this opens up \u201cjust making music\u201d.',
        doThis: ['Learn the shape of major/minor triads; practise switching C-F-G chords smoothly.'],
        examples: ['A 4-chord song (C-G-Am-F).'],
        next: 'Learn to sight-read.',
        claim: 'you can accompany a song with I-IV-V chords.' },
      { level: 17, title: 'Song Repertoire',
        meaning: 'Learn 3 full songs you enjoy, by heart (chords + melody). Build a set you can play any time.',
        why: 'Repertoire keeps it fun and cements everything — playing for real is the best practice.',
        doThis: ['Pick 3 songs you love; learn them fully; keep them polished.'],
        examples: ['A pop song, a film theme, and a short classical piece.'],
        next: 'Sight-reading.',
        claim: 'you can play 3 full songs from memory.' },
      { level: 20, title: 'Sight-Reading & Rhythm',
        meaning: 'Read simple sheet music at sight (grade 1-2) and count rhythms (quarters/eighths) correctly.',
        why: 'Sight-reading makes you independent \u2014 you can pick up any piece without a tutorial.',
        doThis: ['5 min a day sight-reading a new simple piece; count out loud.'],
        examples: ['Grade-1 pieces at sight.'],
        next: 'Hand independence + dynamics.',
        claim: 'you can read an unfamiliar grade-1/2 piece reasonably at sight.' },
      { level: 24, title: 'Two-Hand Independence',
        meaning: 'Pieces where the hands play genuinely different rhythms (a waltz: left hand oom-pah-pah, right hand a flowing melody).',
        why: 'True independence between the hands is what separates beginners from intermediates.',
        doThis: ['Practise a waltz or a broken-chord left hand under a singing right-hand melody.'],
        examples: ['A simple waltz; \u201cRiver Flows in You\u201d.'],
        next: 'Independence, dynamics & pedal.',
        claim: 'you play a piece with clearly independent hand rhythms.' },
      { level: 30, title: 'Independence, Dynamics & Pedal',
        meaning: 'Hands playing different rhythms; playing with dynamics (soft/loud); basic pedal use. An intermediate piece.',
        why: 'Musicality (dynamics, pedal) lifts it from \u201cnotes\u201d to \u201cmusic\u201d.',
        doThis: ['Practise a piece with marked dynamics; add pedal on chord changes.'],
        examples: ['Full \u201cF\u00fcr Elise\u201d; a Clementi sonatina.'],
        next: 'Polish an intermediate piece.',
        claim: 'you play an intermediate piece with dynamics and pedal.' },
      { level: 36, title: 'Phrasing & Half-Pedal',
        meaning: 'Musical phrasing (shaping lines), half-pedalling, and voicing the melody above the accompaniment.',
        why: 'This is where playing becomes expressive and personal, not mechanical.',
        doThis: ['Take a lyrical piece; shape each phrase; practise half-pedal changes.'],
        examples: ['\u201cComptine d\u2019un autre \u00e9t\u00e9\u201d (Am\u00e9lie).'],
        next: 'Intermediate repertoire.',
        claim: 'you play a lyrical piece with real phrasing and pedal control.' },
      { level: 45, title: 'Intermediate Repertoire',
        meaning: 'A full intermediate piece to performance level (e.g. a Chopin prelude or a Bach Invention). All 12 major scales fluent.',
        why: 'Real repertoire + all keys is the mark of a solid intermediate pianist.',
        doThis: ['Pick one intermediate piece and polish it fully; drill all 12 major scales.'],
        examples: ['Bach Invention No. 1; Chopin Prelude in E minor.'],
        next: 'Advanced technique.',
        claim: 'you perform one intermediate piece at level.' },
      { level: 55, title: 'Advanced Intermediate',
        meaning: 'A harder piece (a Chopin waltz or a Debussy miniature) and faster scales/arpeggios in all keys.',
        why: 'Bridges the gap to advanced repertoire.',
        doThis: ['Learn one advanced-intermediate piece; speed up scales in all 12 keys.'],
        examples: ['Chopin Waltz in A minor; Debussy \u201cArabesque\u201d.'],
        next: 'Advanced technique.',
        claim: 'you play an advanced-intermediate piece cleanly.' },
      { level: 70, title: 'Advanced Technique',
        meaning: 'Arpeggios, fast passages, a Chopin nocturne or a Bach fugue.',
        why: 'Advanced technique opens the great repertoire.',
        doThis: ['Daily arpeggio + fast-passage drills; learn one advanced piece.'],
        examples: ['Chopin Nocturne Op. 9 No. 2.'],
        next: 'Mastery.',
        claim: 'you can play an advanced piece.' },
      { level: 85, title: 'Concert Piece',
        meaning: 'A demanding concert-level piece, polished to performance standard.',
        why: 'Performance-ready advanced repertoire is the doorway to mastery.',
        doThis: ['Choose one concert piece and refine it over months to performance level.'],
        examples: ['Debussy \u201cClair de Lune\u201d; a Chopin Ballade excerpt.'],
        next: 'Mastery.',
        claim: 'you perform a concert-level piece.' },
      { level: 100, title: 'Mastery',
        meaning: 'Perform an advanced piece from memory; improvise or accompany by ear.',
        why: 'The final tier: technique + musicianship + freedom.',
        doThis: ['Perform from memory; practise playing along by ear.'],
        examples: ['Perform a full advanced piece; jam along to a song by ear.'],
        next: 'You\u2019ve reached the top \u2014 keep the fire.',
        claim: 'you perform at level and can play by ear.' },
    ],
    puzzling: [
      { level: 1, title: 'First Puzzle',
        meaning: 'Finish a small jigsaw (100-300 pieces). Core method: turn all pieces face-up, find the edge pieces, build the frame.',
        why: 'The border gives you the boundary; sorting before you start is the fundamental skill.',
        doThis: ['Flip all pieces face-up \u2192 separate edges \u2192 build the frame \u2192 fill in.'],
        examples: ['A 300-piece landscape.'],
        next: 'Sort by colour/pattern.',
        claim: 'you finish a 100-300 piece puzzle.' },
      { level: 2, title: 'Sort & Section',
        meaning: 'Finish a 500-piece puzzle by sorting into colour/pattern groups.',
        why: 'Sorting into sections turns chaos into solvable chunks.',
        doThis: ['Group by colour/distinct features \u2192 build recognisable areas \u2192 connect them.'],
        examples: ['A 500-piece image with clear colour blocks.'],
        next: 'The standard 1000.',
        claim: 'you finish a 500-piece puzzle using the sorting method.' },
      { level: 4, title: '1000 Pieces',
        meaning: 'Finish a standard 1000-piece puzzle.',
        why: 'The \u201cstandard\u201d adult puzzle \u2014 a real milestone.',
        doThis: ['Frame \u2192 colour sections \u2192 tricky uniform areas (sky/water) by piece shape.'],
        examples: ['A 1000-piece scene.'],
        next: 'Beat the clock / uniform areas.',
        claim: 'you finish a 1000-piece puzzle.' },
      { level: 6, title: 'Beat the Clock / Uniform Areas',
        meaning: 'Finish a 1000-piece puzzle under your personal best, or one with large uniform areas (sky/sea).',
        why: 'Uniform areas force you to solve by piece shape instead of image \u2014 an advanced skill.',
        doThis: ['Time yourself; or pick a puzzle with a big plain area and solve it by shape.'],
        examples: ['A mostly-sky landscape.'],
        next: '2000 pieces.',
        claim: 'you finish a uniform-area puzzle or beat your 1000 time.' },
      { level: 9, title: '2000 Pieces',
        meaning: 'Finish a 2000-piece puzzle.',
        why: 'More volume = more sorting and memory discipline.',
        doThis: ['Sort into many trays; work section by section over multiple sessions.'],
        examples: ['A 2000-piece detailed image.'],
        next: 'Hard modes.',
        claim: 'you finish a 2000-piece puzzle.' },
      { level: 14, title: 'Hard Modes',
        meaning: 'All-white/gradient puzzles, or shaped/3D puzzles.',
        why: 'With no image you solve purely on shape \u2014 the hardest puzzle thinking.',
        doThis: ['Try an \u201cimpossible\u201d white/gradient puzzle; solve by edge shape alone.'],
        examples: ['A pure-white or gradient puzzle.'],
        next: '5000 pieces / speed.',
        claim: 'you finish a white/gradient \u201cimpossible\u201d puzzle.' },
      { level: 22, title: '5000 Pieces / Speed',
        meaning: 'Finish a 5000-piece puzzle, or reach competitive speed on 1000.',
        why: 'Scale + speed is elite territory.',
        doThis: ['Commit to a 5000 over several weeks, or time-train 1000s.'],
        examples: ['A 5000-piece panorama.'],
        next: 'Master builder.',
        claim: 'you finish a 5000-piece puzzle.' },
      { level: 40, title: 'Master Builder',
        meaning: 'A 10,000+ piece puzzle, or consistent competition times.',
        why: 'Only the dedicated get here.',
        doThis: ['Take on a 10k over a long stretch, or enter a speed event.'],
        examples: ['A 10,000-piece world map.'],
        next: 'Legend.',
        claim: 'you finish a 10,000-piece puzzle.' },
      { level: 100, title: 'Puzzle Legend',
        meaning: 'Multiple 10k+ puzzles, or a podium at a speed-puzzling competition.',
        why: 'The top of the craft.',
        doThis: ['Build a collection of giant puzzles, or compete.'],
        examples: ['Podium at a speed-puzzling event.'],
        next: 'You\u2019ve mastered it.',
        claim: 'you puzzle at competition level.' },
    ],
    drawing: [
      { level: 1, title: 'Marks & Lines', meaning: 'Make controlled marks: straight lines, curves, circles and ovals, drawn from the shoulder/elbow \u2014 not just the wrist.', why: 'Line control is the alphabet of drawing; loose confident lines beat stiff scratchy ones.', doThis: ['Fill a page with lines, then circles/ovals, each in one smooth stroke.'], examples: ['A page of clean circles and parallel lines.'], next: 'Turn shapes into 3D forms.', claim: 'you can draw a smooth straight line and a round circle on demand.' },
      { level: 3, title: 'Shapes to Forms', meaning: 'Turn flat shapes into 3D forms: cube, sphere, cylinder, cone.', why: 'Every object is built from these forms; seeing them lets you draw anything.', doThis: ['Draw each form from a few angles; add a light source and one cast shadow.'], examples: ['A shaded sphere and cube.'], next: 'Proportion & measuring.', claim: 'you can draw the four basic forms with simple shading.' },
      { level: 6, title: 'Proportion & Measuring', meaning: 'Copy a real object with correct proportions using measuring (comparing sizes/angles).', why: 'Accurate proportion is what makes a drawing \u201clook right\u201d.', doThis: ['Draw a still life (mug, bottle) by measuring relationships, not guessing.'], examples: ['A believable still life of 2-3 objects.'], next: 'Light & shading.', claim: 'you can draw a still life with believable proportions.' },
      { level: 10, title: 'Value & Shading', meaning: 'Render light and shadow with a full value range (highlight \u2192 core shadow \u2192 reflected light \u2192 cast shadow).', why: 'Value creates the illusion of 3D and mood \u2014 more than line does.', doThis: ['Shade a sphere and a still life with 5+ values; squint to see big shapes.'], examples: ['A convincingly 3D shaded still life.'], next: 'Perspective.', claim: 'you can shade an object with a smooth, believable value range.' },
      { level: 15, title: '1 & 2-Point Perspective', meaning: 'Draw boxes, rooms and streets in 1- and 2-point perspective with a horizon line and vanishing points.', why: 'Perspective lets you draw believable space and architecture.', doThis: ['Draw a room interior and a street in 2-point perspective.'], examples: ['A believable room in perspective.'], next: 'Gesture & the figure.', claim: 'you can draw a box and a simple room in correct perspective.' },
      { level: 22, title: 'Gesture & Figure Basics', meaning: 'Capture a pose in 30-60s gesture drawings; build the figure from simple forms and proportion (heads-tall).', why: 'The figure is the hardest, most rewarding subject; gesture keeps it alive.', doThis: ['Do 20 quick gesture sketches; then one longer figure using the 7.5-heads proportion.'], examples: ['A page of lively gesture poses.'], next: 'Anatomy & construction.', claim: 'you can capture a believable pose and basic figure proportions.' },
      { level: 32, title: 'Anatomy & Construction', meaning: 'Learn the major muscle/bone landmarks and construct heads and hands.', why: 'Anatomy turns stick-figures into believable people.', doThis: ['Study and draw the skull, torso and hand from reference.'], examples: ['A constructed head from multiple angles.'], next: 'Composition & your style.', claim: 'you can construct a head and hand from imagination.' },
      { level: 45, title: 'Composition & Rendering', meaning: 'Compose a full finished piece (thumbnails \u2192 value study \u2192 render) with strong focal point and design.', why: 'Composition is what separates a study from a picture people stop to look at.', doThis: ['Take one idea from thumbnail to a fully rendered finished drawing.'], examples: ['A finished, composed illustration.'], next: 'Personal voice.', claim: 'you can take an idea to a finished, well-composed drawing.' },
      { level: 70, title: 'Style & Speed', meaning: 'Develop a recognisable personal style; draw fluently and quickly from imagination.', why: 'A voice + speed is what makes an artist, not just a copier.', doThis: ['Do a daily drawing from imagination in your own style for a month.'], examples: ['A cohesive set of pieces in your style.'], next: 'Mastery.', claim: 'you draw fluently from imagination in a recognisable style.' },
      { level: 100, title: 'Mastery', meaning: 'Produce portfolio-level work; draw anything you can imagine.', why: 'The top: technique, imagination and voice united.', doThis: ['Build a portfolio; take commissions or share work publicly.'], examples: ['A portfolio others recognise as yours.'], next: 'Keep creating.', claim: 'you can draw anything convincingly, in your own voice.' },
    ],
    coding: [
      { level: 1, title: 'First Program', meaning: 'Write and run your first program (print output, a variable, basic math) in one language (Python recommended).', why: 'Everything starts with being able to run code and see a result.', doThis: ['Install Python; write a script that prints and does arithmetic; run it.'], examples: ['A script that greets you and adds two numbers.'], next: 'Logic & control flow.', claim: 'you can write and run a small script from scratch.' },
      { level: 3, title: 'Logic & Control Flow', meaning: 'Use variables, if/else, loops (for/while) and basic data types to solve small problems.', why: 'Control flow is how programs make decisions and repeat work \u2014 the core of all code.', doThis: ['Solve 10 small exercises using loops and conditionals.'], examples: ['FizzBuzz; a number-guessing game.'], next: 'Functions & structure.', claim: 'you can solve FizzBuzz and a guessing game on your own.' },
      { level: 6, title: 'Functions & Data Structures', meaning: 'Write functions; use lists/arrays, dictionaries/maps; break a problem into pieces.', why: 'Functions + data structures let you build anything non-trivial without chaos.', doThis: ['Refactor a script into functions; use a dict to count word frequencies.'], examples: ['A word-counter using functions and a dictionary.'], next: 'A real small project.', claim: 'you can write clean functions and use lists/dicts to solve a problem.' },
      { level: 10, title: 'First Real Project', meaning: 'Build a small complete program end-to-end (e.g. a to-do CLI, a simple calculator, a text game).', why: 'Finishing a real project is where scattered skills become ability.', doThis: ['Pick one small app idea and build it fully, start to finish.'], examples: ['A working command-line to-do app.'], next: 'Version control & debugging.', claim: 'you built one small program that actually works.' },
      { level: 15, title: 'Git, Debugging & Reading Docs', meaning: 'Use Git (commit/branch/push), read error messages, use a debugger, and read documentation to solve problems.', why: 'These are the daily survival skills of every real developer.', doThis: ['Put a project on GitHub; fix a bug using the debugger; use a new library from its docs.'], examples: ['A project on GitHub with a clean commit history.'], next: 'Web basics.', claim: 'you use Git and can debug your own code with a debugger.' },
      { level: 22, title: 'Web / App Basics', meaning: 'Build a simple web page or app (HTML/CSS/JS, or a Python web app) that does something useful.', why: 'Shipping something others can use is a huge motivator and a real skill jump.', doThis: ['Build and deploy a simple site or app (like Gamenfy itself!).'], examples: ['A deployed personal site or small web tool.'], next: 'Data & APIs.', claim: 'you built and deployed a small web page or app.' },
      { level: 32, title: 'APIs, Databases & Async', meaning: 'Fetch data from an API, store data in a database, handle async operations.', why: 'Real apps talk to servers and remember data \u2014 this is the backbone.', doThis: ['Build an app that calls an API and saves results to a database.'], examples: ['An app pulling live data and storing it.'], next: 'Clean code & testing.', claim: 'you can build an app that uses an API and a database.' },
      { level: 45, title: 'Clean Code, Testing & Design', meaning: 'Write readable, tested, well-structured code; understand basic design patterns and algorithms/complexity.', why: 'The difference between code that works once and code you can grow.', doThis: ['Add tests to a project; refactor for readability; learn Big-O basics.'], examples: ['A tested, well-structured codebase.'], next: 'Build something people use.', claim: 'you write tested, readable, well-structured code.' },
      { level: 70, title: 'Ship Real Software', meaning: 'Build and ship a non-trivial product that real people use; handle scale, security and maintenance.', why: 'Shipping real software for users is the mark of a real engineer.', doThis: ['Launch a product/tool and maintain it with real users.'], examples: ['A live product with actual users.'], next: 'Mastery.', claim: 'you shipped software that real people use.' },
      { level: 100, title: 'Mastery', meaning: 'Architect complex systems; mentor others; work fluently across the stack.', why: 'The top: you can design, build and lead.', doThis: ['Architect a full system; help others level up.'], examples: ['A system you designed end-to-end.'], next: 'Keep building.', claim: 'you can architect and build complex systems fluently.' },
    ],
    tennis: [
      { level: 1, title: 'Grip & Ready', meaning: 'Learn the continental and eastern forehand grips, the ready position, and the split-step.', why: 'Grip and footwork basics decide everything that follows \u2014 wrong grip caps you fast.', doThis: ['Practise the ready position and split-step; hold each grip correctly.'], examples: ['Shadow-swing with the correct forehand grip.'], next: 'Rally the forehand.', claim: 'you can take the ready position and use the correct forehand grip.' },
      { level: 3, title: 'Forehand Rally', meaning: 'Hit a controlled forehand with a full swing (low-to-high) and keep a rally going.', why: 'The forehand is your main weapon; a reliable one is the foundation.', doThis: ['Rally forehands against a wall or partner, aiming for 10 in a row.'], examples: ['10 forehands in a row over the net.'], next: 'Backhand.', claim: 'you can rally 10 forehands in a row.' },
      { level: 6, title: 'Backhand', meaning: 'Hit a controlled backhand (one- or two-handed) and rally both wings.', why: 'A solid backhand means opponents can\u2019t just attack one side.', doThis: ['Rally backhands; then rally alternating forehand/backhand.'], examples: ['10 backhands in a row.'], next: 'Serve.', claim: 'you can rally 10 backhands in a row.' },
      { level: 10, title: 'The Serve', meaning: 'Develop a reliable serve: toss, trophy position, and a flat/slice serve that lands in.', why: 'The serve is the only shot fully in your control \u2014 and it starts every point.', doThis: ['Practise the toss; hit 20 serves, aiming for consistency in the box.'], examples: ['7/10 first serves in.'], next: 'Volleys & consistency.', claim: 'you land 7 of 10 serves in the box.' },
      { level: 15, title: 'Volleys & Net Play', meaning: 'Hit forehand and backhand volleys with a punch; approach and finish at the net.', why: 'Net skills let you finish points and add pressure.', doThis: ['Practise volleys; play approach-and-volley points.'], examples: ['Clean volleys off both wings.'], next: 'Play full points.', claim: 'you can volley off both wings and finish at the net.' },
      { level: 22, title: 'Consistency & Match Play', meaning: 'Play full sets, keep the ball in play under pressure, and win points through consistency.', why: 'At club level, whoever misses less wins \u2014 consistency beats power.', doThis: ['Play practice sets; track your unforced errors and reduce them.'], examples: ['Winning a set through fewer errors.'], next: 'Spin & placement.', claim: 'you can play a full set and win through consistency.' },
      { level: 32, title: 'Spin, Placement & Tactics', meaning: 'Use topspin/slice deliberately, place shots to corners, and play with a game plan.', why: 'Spin and placement turn rallies into weapons and expose opponents.', doThis: ['Hit with heavy topspin; play targets; build points with a plan.'], examples: ['Constructing a point to a winner.'], next: 'Compete.', claim: 'you can use spin and placement tactically in a match.' },
      { level: 45, title: 'Competitive Play', meaning: 'Compete in club matches/ladders; handle pressure, tactics and different opponents.', why: 'Real competition sharpens every part of your game.', doThis: ['Join a ladder or club competition; play ranked matches.'], examples: ['Wins against varied opponents.'], next: 'Advanced game.', claim: 'you compete and win in club-level matches.' },
      { level: 70, title: 'Advanced Game', meaning: 'All shots reliable under pressure; strong serve, movement and match IQ; win at a high club/regional level.', why: 'The complete player \u2014 few weaknesses left to exploit.', doThis: ['Train movement and serve+1 patterns; compete at a higher level.'], examples: ['Success at regional/high club level.'], next: 'Mastery.', claim: 'you win consistently at a high club level.' },
      { level: 100, title: 'Mastery', meaning: 'Tournament-level tennis: elite consistency, weapons, fitness and mentality.', why: 'The top of the amateur game.', doThis: ['Compete at tournament level; train like an athlete.'], examples: ['Tournament results.'], next: 'Keep competing.', claim: 'you play and win at tournament level.' },
    ],
    languages: [
      { level: 1, title: 'First 100 Words', meaning: 'Learn the 100 most common words + basic greetings and pronunciation of your target language.', why: 'The top 100 words make up a huge share of everyday speech; pronunciation habits set early.', doThis: ['Use a flashcard app 10 min/day; learn greetings and say them out loud.'], examples: ['Introduce yourself in the language.'], next: 'Basic sentences.', claim: 'you know ~100 words and can greet + introduce yourself.' },
      { level: 3, title: 'Basic Sentences', meaning: 'Form simple present-tense sentences (I want, I have, where is\u2026) and ask basic questions.', why: 'Sentence patterns let you say new things, not just memorised phrases.', doThis: ['Learn present tense of a few key verbs; build 20 sentences.'], examples: ['Order a coffee; ask for directions.'], next: 'Survival conversation.', claim: 'you can make simple present-tense sentences and ask questions.' },
      { level: 6, title: 'Survival Conversation', meaning: 'Handle everyday situations: shopping, ordering, small talk (~500 words, past/future basics).', why: 'This is the level where the language becomes actually useful.', doThis: ['Practise real dialogues; add past and future tense.'], examples: ['A 2-minute chat with a native speaker.'], next: 'Listening & comprehension.', claim: 'you can survive a basic conversation with a native speaker.' },
      { level: 10, title: 'Listening & Reading', meaning: 'Understand slow speech and simple texts; grow to ~1000-1500 words.', why: 'Input (listening/reading) is what actually builds fluency \u2014 more than grammar drills.', doThis: ['Watch/listen to easy content daily; read simple stories.'], examples: ['Follow a slow podcast; read a graded reader.'], next: 'Conversational fluency.', claim: 'you understand slow speech and simple texts.' },
      { level: 18, title: 'Conversational Fluency', meaning: 'Hold a real conversation on familiar topics; ~3000 words; think less about grammar.', why: 'The tipping point where you use the language instead of translating.', doThis: ['Speak weekly with a tutor/partner; narrate your day in the language.'], examples: ['A 15-min conversation without switching to English.'], next: 'Complex topics.', claim: 'you can hold a real conversation on familiar topics.' },
      { level: 30, title: 'Complex Topics & Media', meaning: 'Discuss abstract topics, follow native media (shows, news) at natural speed.', why: 'Understanding native content unlocks the whole culture.', doThis: ['Watch native shows without subtitles; discuss opinions.'], examples: ['Follow a TV show without subtitles.'], next: 'Advanced fluency.', claim: 'you follow native media and discuss abstract topics.' },
      { level: 50, title: 'Advanced Fluency', meaning: 'Express nuance, understand idioms/slang, read novels; near-effortless daily use.', why: 'This is comfortable, natural mastery.', doThis: ['Read a novel; use idioms; write longer texts.'], examples: ['Finish a novel in the language.'], next: 'Native-like.', claim: 'you use the language nearly effortlessly, including nuance.' },
      { level: 75, title: 'Near-Native', meaning: 'Understand nearly everything, express yourself precisely, few noticeable gaps.', why: 'Near-native command opens work and deep relationships.', doThis: ['Immerse fully; work/socialise in the language.'], examples: ['Handle a work meeting in the language.'], next: 'Mastery.', claim: 'you operate near-natively in any everyday context.' },
      { level: 100, title: 'Mastery', meaning: 'Full command including humour, register and culture; mistaken for a native.', why: 'The top: the language is truly yours.', doThis: ['Live in it; master register and humour.'], examples: ['Get mistaken for a native.'], next: 'Learn the next language.', claim: 'you have full, native-like command.' },
    ],
    cooking: [
      { level: 1, title: 'Kitchen Basics', meaning: 'Knife safety + basic cuts, kitchen setup, and cooking 3 simple meals (eggs, pasta, rice).', why: 'Safe knife skills and a few reliable meals are the foundation of everything.', doThis: ['Learn the claw grip; cook eggs, pasta and rice well.'], examples: ['A perfect scrambled egg; al dente pasta.'], next: 'Flavour basics.', claim: 'you can safely chop and cook 3 simple meals well.' },
      { level: 3, title: 'Flavour & Seasoning', meaning: 'Season properly (salt/acid/fat/heat), taste as you go, build simple sauces.', why: 'Seasoning is the difference between bland and delicious \u2014 the real cooking skill.', doThis: ['Cook the same dish and adjust salt/acid until it pops; make a pan sauce.'], examples: ['A simple garlic-butter or tomato sauce.'], next: 'Cook without recipes.', claim: 'you can season a dish to taste and make a basic sauce.' },
      { level: 6, title: 'Cook 5 Solid Meals', meaning: 'Have 5 go-to meals you can cook confidently from memory (stir-fry, roast, soup\u2026).', why: 'A repertoire means you eat well any night without thinking.', doThis: ['Nail 5 varied meals until you can cook them without a recipe.'], examples: ['A stir-fry, a roast chicken, a soup.'], next: 'Techniques.', claim: 'you can cook 5 varied meals from memory.' },
      { level: 10, title: 'Core Techniques', meaning: 'Master searing, roasting, braising, sauteing, emulsifying \u2014 techniques, not just recipes.', why: 'Techniques let you cook anything, not just what you memorised.', doThis: ['Practise each technique on a simple ingredient.'], examples: ['A properly seared steak; a braise.'], next: 'Improvise.', claim: 'you can sear, roast and braise reliably.' },
      { level: 18, title: 'Cook Without Recipes', meaning: 'Open the fridge and make something good from what you have; balance a plate.', why: 'True cooking freedom \u2014 you create instead of follow.', doThis: ['Once a week, cook using only what you already have.'], examples: ['A tasty improvised dinner from leftovers.'], next: 'Host a meal.', claim: 'you can improvise a good meal from whatever you have.' },
      { level: 30, title: 'Multi-Course & Hosting', meaning: 'Plan and cook a multi-course meal with timing so everything is ready together.', why: 'Timing and hosting are the mark of a real cook.', doThis: ['Cook a 3-course dinner for friends, timed right.'], examples: ['A 3-course dinner served hot and on time.'], next: 'Cuisines & baking.', claim: 'you can plan and serve a multi-course meal.' },
      { level: 50, title: 'Cuisines & Baking', meaning: 'Cook confidently across cuisines; handle baking/pastry (bread, dessert) which demands precision.', why: 'Breadth + baking precision rounds out a complete cook.', doThis: ['Learn 3 cuisines; bake bread and one dessert from scratch.'], examples: ['Homemade bread; a plated dessert.'], next: 'Signature level.', claim: 'you cook across cuisines and bake from scratch.' },
      { level: 75, title: 'Signature Cook', meaning: 'Develop signature dishes; adapt and refine recipes; restaurant-quality plating.', why: 'Your own voice in the kitchen.', doThis: ['Create and refine 3 signature dishes.'], examples: ['A signature dish people request.'], next: 'Mastery.', claim: 'you have refined signature dishes at high quality.' },
      { level: 100, title: 'Mastery', meaning: 'Cook anything to a high standard; create dishes; teach others.', why: 'The top: creativity, technique and consistency.', doThis: ['Create original dishes; host regularly; teach someone.'], examples: ['A menu of your own creations.'], next: 'Keep cooking.', claim: 'you can cook and create anything to a high standard.' },
    ],
    calisthenics: [
      { level: 1, title: 'Foundations', meaning: 'Build the base: push-ups (from knees if needed), bodyweight squats, planks, and active hangs.', why: 'A solid base prevents injury and unlocks every harder move.', doThis: ['3x/week: push-ups, squats, 30s plank, 20s hang.'], examples: ['10 clean push-ups; 30s plank.'], next: 'Full push-ups & rows.', claim: 'you can do 10 push-ups and a 30s plank.' },
      { level: 3, title: 'Push & Pull', meaning: 'Full push-ups (sets of 15+), inverted rows / negative pull-ups, dips.', why: 'Balanced push and pull is the core of upper-body calisthenics.', doThis: ['Progress push-ups to 15+; train rows and dip negatives.'], examples: ['15 push-ups; 8 inverted rows.'], next: 'First pull-up.', claim: 'you can do 15 push-ups and 8 rows.' },
      { level: 6, title: 'First Pull-Up', meaning: 'Achieve your first strict pull-up, then build to 5.', why: 'The pull-up is the milestone that marks real upper-body strength.', doThis: ['Train negatives + band pull-ups until you get 1, then build reps.'], examples: ['1 strict pull-up \u2192 5.'], next: 'Core & L-sit.', claim: 'you can do 5 strict pull-ups.' },
      { level: 10, title: 'Core & L-Sit', meaning: 'Strong core work: hanging leg raises, hollow holds, and progress toward an L-sit.', why: 'A strong core is the link for all advanced moves.', doThis: ['Train hollow holds, leg raises, tuck L-sits.'], examples: ['A 10s L-sit.'], next: 'Dips & pistol prep.', claim: 'you can hold a tuck L-sit and do 10 hanging leg raises.' },
      { level: 18, title: 'Dips, Pistols & Volume', meaning: 'Weighted-feel dips, pistol-squat progressions, and higher volume across push/pull.', why: 'Unilateral strength + volume builds real, usable power.', doThis: ['Train pistol progressions; hit 12+ dips and 10+ pull-ups.'], examples: ['A clean pistol squat.'], next: 'First skill move.', claim: 'you can do a pistol squat and 10 pull-ups.' },
      { level: 30, title: 'First Skill (L-Sit / Handstand)', meaning: 'Hold a full L-sit and a wall handstand; start straight-bar/muscle-up prep.', why: 'Skills are where calisthenics becomes impressive and fun.', doThis: ['Train handstand against the wall daily; full L-sit.'], examples: ['A 20s wall handstand.'], next: 'Muscle-up.', claim: 'you can hold a full L-sit and a wall handstand.' },
      { level: 45, title: 'Muscle-Up', meaning: 'Achieve a clean bar (or ring) muscle-up.', why: 'The muscle-up is a landmark full-body skill.', doThis: ['Train explosive pull-ups + transitions until you get it.'], examples: ['One clean muscle-up.'], next: 'Freestanding handstand.', claim: 'you can do a clean muscle-up.' },
      { level: 60, title: 'Freestanding Handstand', meaning: 'Hold a freestanding handstand (10s+) and press-work.', why: 'Balance + strength mastery.', doThis: ['Daily handstand practice away from the wall.'], examples: ['A 10s freestanding handstand.'], next: 'Advanced statics.', claim: 'you can hold a freestanding handstand.' },
      { level: 80, title: 'Advanced Statics', meaning: 'Work toward a front lever, back lever or planche progressions.', why: 'Elite straight-arm strength.', doThis: ['Train lever/planche progressions consistently.'], examples: ['A tuck front lever hold.'], next: 'Mastery.', claim: 'you can hold an advanced static (e.g. tuck front lever).' },
      { level: 100, title: 'Mastery', meaning: 'Own multiple advanced skills (levers, planche, handstand press) with control.', why: 'The top of bodyweight strength.', doThis: ['Combine skills into flows; keep progressing.'], examples: ['A full lever/planche.'], next: 'Keep training.', claim: 'you own advanced static strength skills.' },
    ],
    core: [
      { level: 1, title: 'Brace & Plank', meaning: 'Learn to brace the core and hold a solid plank (30s) with a neutral spine.', why: 'A braced core protects your back and powers every movement.', doThis: ['Practise bracing; hold planks with good form.'], examples: ['A 30s plank without sagging.'], next: 'Anti-rotation.', claim: 'you can hold a 30s plank with a neutral spine.' },
      { level: 3, title: 'Dead Bugs & Anti-Rotation', meaning: 'Dead bugs, bird-dogs and Pallof-press style anti-rotation control.', why: 'Real core strength is resisting movement, not just crunching.', doThis: ['Train dead bugs and anti-rotation holds.'], examples: ['Slow controlled dead bugs.'], next: 'Hollow hold.', claim: 'you can do controlled dead bugs and hold anti-rotation.' },
      { level: 6, title: 'Hollow Hold & Leg Raises', meaning: 'Hollow-body hold (30s) and lying/hanging leg raises.', why: 'The hollow is the foundation of all gymnastics core work.', doThis: ['Train hollow holds and leg raises.'], examples: ['A 30s hollow hold.'], next: 'Hanging core.', claim: 'you can hold a 30s hollow and do 12 leg raises.' },
      { level: 10, title: 'Hanging Core', meaning: 'Hanging knee/leg raises with control; toes-to-bar progression.', why: 'Hanging core links grip, lats and abs \u2014 highly functional.', doThis: ['Train hanging leg raises toward toes-to-bar.'], examples: ['10 hanging leg raises.'], next: 'L-sit.', claim: 'you can do 10 controlled hanging leg raises.' },
      { level: 18, title: 'L-Sit', meaning: 'Hold a tuck L-sit, then a full L-sit (10s).', why: 'The L-sit is a true measure of core + hip-flexor strength.', doThis: ['Train tuck \u2192 full L-sit holds.'], examples: ['A 10s L-sit.'], next: 'Dragon flag.', claim: 'you can hold a 10s L-sit.' },
      { level: 30, title: 'Dragon Flag / V-Sit', meaning: 'Work the dragon flag and V-sit \u2014 advanced whole-body core control.', why: 'These separate strong cores from elite ones.', doThis: ['Train dragon-flag negatives and V-sit progressions.'], examples: ['A slow dragon-flag negative.'], next: 'Front lever core.', claim: 'you can do a controlled dragon-flag negative.' },
      { level: 50, title: 'Front-Lever Core', meaning: 'Core strength for a tuck/adv-tuck front lever hold.', why: 'Elite straight-body core tension.', doThis: ['Train front-lever progressions.'], examples: ['A tuck front lever.'], next: 'Mastery.', claim: 'you can hold a tuck front lever.' },
      { level: 75, title: 'Elite Core', meaning: 'Full dragon flag, V-sit, advanced lever core with control.', why: 'Near the top of core strength.', doThis: ['Own the full dragon flag and V-sit.'], examples: ['A full dragon flag.'], next: 'Mastery.', claim: 'you own the full dragon flag and V-sit.' },
      { level: 100, title: 'Mastery', meaning: 'Complete core control across all advanced holds and dynamic movements.', why: 'The top of core strength.', doThis: ['Combine advanced core skills into flows.'], examples: ['Advanced core skills on demand.'], next: 'Keep training.', claim: 'you have complete advanced core control.' },
    ],
    strength: [
      { level: 1, title: 'Learn the Lifts', meaning: 'Learn clean form on your main lifts (bench, row, hip thrust, overhead press, lat pulldown) with light weight.', why: 'Form first \u2014 it prevents injury and is the base of all strength.', doThis: ['Drill form with an empty/light bar; film yourself.'], examples: ['Clean form on bench and row.'], next: 'Progressive overload.', claim: 'you can perform your main lifts with clean form.' },
      { level: 3, title: 'Progressive Overload', meaning: 'Add weight/reps consistently each week; track your lifts.', why: 'Progressive overload is THE mechanism of getting stronger.', doThis: ['Log every session; add a little each week.'], examples: ['4 weeks of steady progress logged.'], next: 'Bodyweight bench.', claim: 'you are consistently adding weight/reps and tracking it.' },
      { level: 6, title: 'Solid Base Numbers', meaning: 'Reach a respectable base (e.g. bench ~0.75x bodyweight, strong rows and presses).', why: 'A base level of strength changes how your body looks and feels.', doThis: ['Push your main lifts toward beginner-strength standards.'], examples: ['Bench ~0.75x bodyweight.'], next: 'Bodyweight lifts.', claim: 'you hit beginner strength standards on your main lifts.' },
      { level: 10, title: 'Bodyweight Lifts', meaning: 'Bench ~1x bodyweight; strong overhead press and rows.', why: 'Bodyweight-bench is a classic intermediate milestone.', doThis: ['Train toward a bodyweight bench with good programming.'], examples: ['Bench 1x bodyweight.'], next: 'Intermediate program.', claim: 'you can bench roughly your bodyweight.' },
      { level: 18, title: 'Intermediate Strength', meaning: 'Follow a proper intermediate program; hit intermediate standards on all lifts.', why: 'Structured programming is needed once easy gains slow down.', doThis: ['Run a proven intermediate program for a full cycle.'], examples: ['Intermediate standards across lifts.'], next: 'Advanced pressing.', claim: 'you meet intermediate strength standards on your lifts.' },
      { level: 30, title: 'Advanced Pressing & Pulling', meaning: 'Bench ~1.25-1.5x bodyweight; strong weighted pull-ups/rows.', why: 'Advanced upper-body numbers take real dedication.', doThis: ['Periodise; push toward advanced standards.'], examples: ['Bench 1.25x bodyweight.'], next: 'Elite programming.', claim: 'you reach advanced upper-body strength standards.' },
      { level: 50, title: 'Elite Numbers', meaning: 'Approach elite standards on your main lifts with smart periodisation and recovery.', why: 'Elite strength requires managing fatigue, not just training hard.', doThis: ['Periodise carefully; prioritise recovery and technique.'], examples: ['Near-elite lift numbers.'], next: 'Mastery.', claim: 'you approach elite strength standards.' },
      { level: 75, title: 'Near-Elite', meaning: 'Elite-level strength maintained with excellent technique and longevity.', why: 'Sustained elite strength is rare and hard-won.', doThis: ['Maintain elite lifts injury-free.'], examples: ['Elite lifts, healthy joints.'], next: 'Mastery.', claim: 'you maintain elite strength with clean technique.' },
      { level: 100, title: 'Mastery', meaning: 'Peak strength for your frame, maintained for the long term; you could coach others.', why: 'The top: strength + knowledge + longevity.', doThis: ['Peak and maintain; help others train.'], examples: ['Peak lifts you can teach.'], next: 'Stay strong for life.', claim: 'you have peak, sustainable strength and can coach it.' },
    ],
    dancing: [
      { level: 1, title: 'Feel the Beat', meaning: 'Find and stay on the beat; basic bounce/groove and body relaxation.', why: 'Musicality (being on beat) is the foundation \u2014 without it, moves look off.', doThis: ['Nod/step on the beat to songs; loosen up; count 8s.'], examples: ['Stay on beat through a full song.'], next: 'Basic steps.', claim: 'you can consistently stay on the beat.' },
      { level: 3, title: 'Basic Steps', meaning: 'Learn a handful of basic steps in your style (two-step, box step, basic footwork).', why: 'A few solid basics give you something to always fall back on.', doThis: ['Drill 3-4 basic steps until automatic.'], examples: ['Clean basic steps to music.'], next: 'Short combo.', claim: 'you can do 3-4 basic steps cleanly on beat.' },
      { level: 6, title: 'First Combo', meaning: 'String steps into a short 8-16 count combo and perform it smoothly.', why: 'Combos train memory, flow and transitions.', doThis: ['Learn and drill one short choreography.'], examples: ['A clean 16-count combo.'], next: 'Musicality & control.', claim: 'you can perform a short combo smoothly.' },
      { level: 10, title: 'Control & Musicality', meaning: 'Add dynamics: hit accents, control speed, isolate body parts.', why: 'Hitting the music (accents/pauses) is what makes dancing look good.', doThis: ['Practise isolations; hit the beats and pauses in a song.'], examples: ['Hitting accents in a routine.'], next: 'Freestyle basics.', claim: 'you can hit accents and control your movement.' },
      { level: 18, title: 'Freestyle Basics', meaning: 'Freestyle for 30-60s without freezing, mixing your steps to any song.', why: 'Freestyle is where dance becomes yours, not just memorised.', doThis: ['Freestyle to random songs daily, even badly.'], examples: ['A 1-minute freestyle that flows.'], next: 'Full routine.', claim: 'you can freestyle for a minute without freezing.' },
      { level: 30, title: 'Full Routine', meaning: 'Learn and perform a full-song choreography with clean execution.', why: 'A full routine tests stamina, memory and performance.', doThis: ['Learn a full choreo; polish it to performance level.'], examples: ['A full-song routine performed clean.'], next: 'Style & performance.', claim: 'you can perform a full-song choreography.' },
      { level: 50, title: 'Style & Performance', meaning: 'Develop your personal style, stage presence and clean technique.', why: 'Presence + style separate a dancer from someone doing moves.', doThis: ['Perform for others; film and refine your style.'], examples: ['A performance with real presence.'], next: 'Advanced.', claim: 'you perform with clean technique and real presence.' },
      { level: 75, title: 'Advanced Dancer', meaning: 'Handle advanced choreography and battles/freestyle at a high level.', why: 'High-level control, creativity and adaptability.', doThis: ['Battle or perform at a high level; keep learning styles.'], examples: ['Holding your own in a battle.'], next: 'Mastery.', claim: 'you dance advanced choreo and freestyle at a high level.' },
      { level: 100, title: 'Mastery', meaning: 'Command multiple styles, choreograph, and move others with your dancing.', why: 'The top: technique, creativity and expression united.', doThis: ['Choreograph; teach; perform.'], examples: ['A routine you choreographed and performed.'], next: 'Keep dancing.', claim: 'you master multiple styles and can choreograph.' },
    ],
    sales: [
      { level: 1, title: 'Mindset & Belief', meaning: 'Understand sales as helping, not pushing; believe in what you offer.', why: 'People buy from those who believe and genuinely help \u2014 mindset comes first.', doThis: ['Write why your thing genuinely helps people; reframe selling as serving.'], examples: ['A clear reason your offer helps.'], next: 'Talk to people.', claim: 'you can explain why what you sell genuinely helps.' },
      { level: 3, title: 'Talk to Strangers', meaning: 'Comfortably start conversations and ask about people\u2019s needs/problems.', why: 'Sales is conversations; comfort talking to strangers is the base skill.', doThis: ['Start 3 conversations a day; ask about their situation.'], examples: ['A natural chat with a stranger.'], next: 'Listen & qualify.', claim: 'you can comfortably start a conversation with a stranger.' },
      { level: 6, title: 'Listen & Qualify', meaning: 'Ask good questions, listen for the real need, and qualify whether you can help.', why: 'The best salespeople listen more than they talk.', doThis: ['Practise open questions; summarise back what someone needs.'], examples: ['Uncovering someone\u2019s real problem.'], next: 'Pitch & value.', claim: 'you can uncover someone\u2019s real need by listening.' },
      { level: 10, title: 'Pitch the Value', meaning: 'Present your offer around their need, focusing on outcomes/value not features.', why: 'People buy outcomes, not features \u2014 framing is everything.', doThis: ['Craft a value-focused pitch tied to a real need.'], examples: ['A pitch that speaks to outcomes.'], next: 'Handle objections.', claim: 'you can pitch value tied to a real need.' },
      { level: 18, title: 'Handle Objections & Close', meaning: 'Address concerns calmly and ask for the sale (close) without pressure.', why: 'Most sales are lost by never asking; closing is a learnable skill.', doThis: ['Practise common objections; practise asking for the close.'], examples: ['Turning a \u201cmaybe\u201d into a yes.'], next: 'First real sales.', claim: 'you can handle objections and confidently ask for the sale.' },
      { level: 30, title: 'Consistent Closer', meaning: 'Close consistently; follow up; build a simple pipeline.', why: 'Consistency + follow-up is where real income comes from.', doThis: ['Track leads; follow up; measure your close rate.'], examples: ['A tracked pipeline with closes.'], next: 'Advanced selling.', claim: 'you close consistently and follow up on leads.' },
      { level: 50, title: 'Advanced Selling', meaning: 'Sell higher-value offers, negotiate, and build long-term relationships.', why: 'High-ticket + relationships is where sales becomes lucrative.', doThis: ['Sell a higher-value offer; negotiate terms.'], examples: ['A high-value deal closed.'], next: 'Master seller.', claim: 'you can close higher-value deals and negotiate.' },
      { level: 75, title: 'Master Seller', meaning: 'Reliably hit targets, build referrals, and could train others.', why: 'Predictable results + a referral engine.', doThis: ['Build referrals; mentor a beginner.'], examples: ['A referral-driven pipeline.'], next: 'Mastery.', claim: 'you hit targets reliably and generate referrals.' },
      { level: 100, title: 'Mastery', meaning: 'Sell anything ethically at scale; build and lead sales.', why: 'The top: results, ethics and leadership.', doThis: ['Scale or lead a sales effort.'], examples: ['A sales system you built.'], next: 'Keep serving.', claim: 'you can sell at scale and lead others.' },
    ],
    marketing: [
      { level: 1, title: 'Know the Customer', meaning: 'Define who you serve and the problem they have (a clear target + pain point).', why: 'Marketing to \u201ceveryone\u201d reaches no one; clarity on the customer drives all of it.', doThis: ['Write a one-line customer + their #1 problem.'], examples: ['\u201cBusy parents who can\u2019t find time to cook.\u201d'], next: 'The message.', claim: 'you can name your target customer and their core problem.' },
      { level: 3, title: 'Craft the Message', meaning: 'Write a clear value proposition and hook that speaks to that problem.', why: 'A sharp message is the core of all marketing.', doThis: ['Write 10 hooks; pick the clearest one.'], examples: ['A one-line value prop that lands.'], next: 'Pick a channel.', claim: 'you can write a clear value proposition and hook.' },
      { level: 6, title: 'One Channel', meaning: 'Pick one channel (social, content, ads, email) and post/publish consistently.', why: 'Depth on one channel beats being everywhere badly.', doThis: ['Post consistently on one channel for 30 days.'], examples: ['30 days of consistent posts.'], next: 'Content that converts.', claim: 'you consistently publish on one channel.' },
      { level: 10, title: 'Content That Converts', meaning: 'Create content that gets attention AND drives an action (follow, sign-up, buy).', why: 'Attention without a call-to-action is just noise.', doThis: ['Add clear CTAs; track which content converts.'], examples: ['A post that drove sign-ups.'], next: 'Funnels & email.', claim: 'you can make content that drives a real action.' },
      { level: 18, title: 'Funnels & Email', meaning: 'Build a simple funnel (attract \u2192 capture \u2192 nurture \u2192 convert) with an email list.', why: 'A funnel turns strangers into customers systematically.', doThis: ['Set up a lead magnet + email sequence.'], examples: ['A working lead-magnet funnel.'], next: 'Data & optimisation.', claim: 'you have a working funnel with an email list.' },
      { level: 30, title: 'Data & Optimisation', meaning: 'Read analytics, A/B test, and improve conversion based on data.', why: 'Marketing is a measurable game \u2014 data beats guessing.', doThis: ['Track a funnel; run an A/B test; improve a number.'], examples: ['A conversion rate you improved.'], next: 'Paid & scale.', claim: 'you can read analytics and A/B test to improve results.' },
      { level: 50, title: 'Paid & Scale', meaning: 'Run profitable paid ads; scale what works across channels.', why: 'Paid + systems is how marketing scales beyond your time.', doThis: ['Run a small profitable ad campaign.'], examples: ['A profitable ad campaign.'], next: 'Brand & strategy.', claim: 'you can run profitable paid ads.' },
      { level: 75, title: 'Brand & Strategy', meaning: 'Build a brand and a full go-to-market strategy across channels.', why: 'Strategy + brand is what separates marketers from posters.', doThis: ['Build a brand + multi-channel strategy.'], examples: ['A coherent brand strategy.'], next: 'Mastery.', claim: 'you can build a brand and a multi-channel strategy.' },
      { level: 100, title: 'Mastery', meaning: 'Market anything profitably; build systems and lead marketing.', why: 'The top: strategy, systems and results.', doThis: ['Lead a full marketing effort.'], examples: ['A marketing system you built.'], next: 'Keep growing.', claim: 'you can market anything profitably and lead it.' },
    ],
    ai_tools: [
      { level: 1, title: 'First Prompts', meaning: 'Use an AI chatbot for real tasks (writing, questions, summaries) and get useful output.', why: 'AI fluency is becoming as basic as knowing how to search.', doThis: ['Use AI daily for real tasks; notice what works.'], examples: ['Draft an email with AI.'], next: 'Better prompting.', claim: 'you use AI for real everyday tasks and get useful results.' },
      { level: 3, title: 'Prompt Engineering', meaning: 'Write clear prompts with context, role, examples and format; iterate to improve output.', why: 'The quality of your prompt largely decides the quality of the output.', doThis: ['Add context/examples/format to prompts; iterate.'], examples: ['A prompt that reliably gives what you want.'], next: 'Workflows.', claim: 'you can write structured prompts and iterate to good results.' },
      { level: 6, title: 'AI Workflows', meaning: 'Chain AI into real workflows: research, drafting, editing, planning.', why: 'AI pays off when it is part of how you work, not a novelty.', doThis: ['Build a repeatable AI workflow for a task you do often.'], examples: ['An AI-assisted content workflow.'], next: 'Tools & assistants.', claim: 'you use AI as part of a repeatable workflow.' },
      { level: 10, title: 'Tools & Custom Assistants', meaning: 'Use image/audio/code AI tools and set up custom assistants/GPTs for your needs.', why: 'The ecosystem beyond chat multiplies what you can do.', doThis: ['Try image/code tools; build a custom assistant.'], examples: ['A custom assistant you use.'], next: 'Automation.', claim: 'you use multiple AI tools and a custom assistant.' },
      { level: 18, title: 'Automation & APIs', meaning: 'Connect AI via APIs / automation tools to do work automatically.', why: 'Automation is where AI saves serious time.', doThis: ['Automate a task using an AI API or no-code tool.'], examples: ['An automated AI task.'], next: 'Build with AI.', claim: 'you can automate a task using AI APIs/tools.' },
      { level: 30, title: 'Build With AI', meaning: 'Build a small app/tool powered by AI (like Gamenfy\u2019s Jarvis).', why: 'Building with AI turns it from user to creator.', doThis: ['Build a small AI-powered feature or tool.'], examples: ['An AI feature you built.'], next: 'Advanced & agents.', claim: 'you built something powered by AI.' },
      { level: 50, title: 'Advanced & Agents', meaning: 'Use advanced techniques (RAG, agents, fine-tuning basics) for real problems.', why: 'Advanced AI unlocks harder, higher-value use cases.', doThis: ['Build a retrieval/agent workflow.'], examples: ['An agentic workflow.'], next: 'AI leader.', claim: 'you can build advanced AI workflows (RAG/agents).' },
      { level: 75, title: 'AI Leader', meaning: 'Design AI solutions for real value; stay ahead of a fast field.', why: 'Leading with AI is a rare, valuable edge.', doThis: ['Ship an AI solution that creates real value.'], examples: ['An AI product with users.'], next: 'Mastery.', claim: 'you design AI solutions that create real value.' },
      { level: 100, title: 'Mastery', meaning: 'Fluent across the AI landscape; build and lead AI-driven work.', why: 'The top: creator and leader in AI.', doThis: ['Lead AI-driven projects.'], examples: ['AI systems you architect.'], next: 'Keep up with the field.', claim: 'you are fluent and can lead AI-driven work.' },
    ],
    content: [
      { level: 1, title: 'Just Post', meaning: 'Publish your first pieces of content \u2014 done beats perfect. Learn your tool (camera/editor).', why: 'The only way to start is to start; volume early builds the skill.', doThis: ['Post 5 pieces of content this week, imperfect is fine.'], examples: ['Your first 5 posts/videos.'], next: 'Hook & retention.', claim: 'you have published your first pieces of content.' },
      { level: 3, title: 'Hooks & Retention', meaning: 'Open strong (first 3 seconds) and keep attention to the end.', why: 'The hook decides whether anyone sees the rest.', doThis: ['Rewrite your openings; study what makes you keep watching.'], examples: ['A post with a strong hook.'], next: 'Consistency.', claim: 'you can write a hook that grabs attention.' },
      { level: 6, title: 'Consistency', meaning: 'Post consistently on a schedule for a month; find your niche/voice.', why: 'Algorithms and audiences reward consistency.', doThis: ['Post on a set schedule for 30 days.'], examples: ['30 days of consistent posting.'], next: 'Quality & editing.', claim: 'you posted consistently for a month.' },
      { level: 10, title: 'Quality & Editing', meaning: 'Improve production: editing, pacing, sound, visuals \u2014 make it look/sound good.', why: 'Better production compounds attention and trust.', doThis: ['Level up your editing and pacing on each post.'], examples: ['A noticeably higher-quality piece.'], next: 'Grow an audience.', claim: 'you can edit content to a good quality bar.' },
      { level: 18, title: 'Grow an Audience', meaning: 'Reach your first real audience (e.g. 1k followers) through content that resonates.', why: 'An audience is the asset everything else builds on.', doThis: ['Double down on what resonates; engage your audience.'], examples: ['Your first 1,000 followers.'], next: 'Content strategy.', claim: 'you grew a real audience (~1k) with your content.' },
      { level: 30, title: 'Strategy & Series', meaning: 'Plan content strategically (series, pillars, funnels) rather than random posts.', why: 'Strategy turns scattered posts into growth.', doThis: ['Build content pillars and a series people follow.'], examples: ['A series people come back for.'], next: 'Monetise.', claim: 'you plan content strategically with pillars/series.' },
      { level: 50, title: 'Monetise', meaning: 'Turn content into income (sponsors, products, services).', why: 'Monetisation makes content sustainable.', doThis: ['Launch a product/offer or land a sponsor.'], examples: ['First income from content.'], next: 'Scale.', claim: 'you earn income from your content.' },
      { level: 75, title: 'Scale & Systems', meaning: 'Systematise creation (batching, team/tools) and scale reach + income.', why: 'Systems let content grow beyond your solo effort.', doThis: ['Batch and systematise; scale reach.'], examples: ['A content system that scales.'], next: 'Mastery.', claim: 'you run a content system that scales.' },
      { level: 100, title: 'Mastery', meaning: 'A strong brand, large audience and reliable income from content.', why: 'The top: influence + income + systems.', doThis: ['Lead a content brand.'], examples: ['A content brand you built.'], next: 'Keep creating.', claim: 'you built a content brand with audience and income.' },
    ],
    learning: [
      { level: 1, title: 'Learn How to Learn', meaning: 'Understand active recall and spaced repetition \u2014 the two most proven study methods.', why: 'How you learn matters more than how long; these methods are backed by strong evidence.', doThis: ['Replace re-reading with self-testing; space your reviews.'], examples: ['Quizzing yourself instead of re-reading.'], next: 'Focus & deep work.', claim: 'you use active recall and spaced repetition to study.' },
      { level: 3, title: 'Focus & Deep Work', meaning: 'Do focused, distraction-free study blocks (e.g. Pomodoro) and beat procrastination.', why: 'Deep focus is where real learning happens; distraction kills it.', doThis: ['Do daily focused blocks; remove distractions.'], examples: ['A 50-min distraction-free study block.'], next: 'Note-taking.', claim: 'you can do focused, distraction-free study blocks.' },
      { level: 6, title: 'Effective Notes', meaning: 'Take notes that build understanding (summarising, connecting, in your own words).', why: 'Good notes are thinking on paper, not transcription.', doThis: ['Summarise in your own words; connect ideas.'], examples: ['Notes that explain, not just copy.'], next: 'Learn a topic fast.', claim: 'you take notes that build real understanding.' },
      { level: 10, title: 'Learn a Topic Fast', meaning: 'Take a new topic from zero to solid understanding efficiently.', why: 'Fast, structured learning is a superpower for everything else.', doThis: ['Pick a topic; go zero-to-competent with a plan.'], examples: ['A topic you learned quickly and can explain.'], next: 'Teach it.', claim: 'you can take a topic from zero to solid understanding efficiently.' },
      { level: 18, title: 'Teach to Learn', meaning: 'Explain what you learn to others (the Feynman technique) to find and fix gaps.', why: 'If you can teach it simply, you truly understand it.', doThis: ['Explain a topic simply to someone (or on paper).'], examples: ['Teaching a concept clearly.'], next: 'Retain long-term.', claim: 'you can teach a topic simply and clearly.' },
      { level: 30, title: 'Long-Term Retention', meaning: 'Build systems (spaced repetition, notes/second brain) so knowledge sticks.', why: 'Learning that fades is wasted; systems keep it.', doThis: ['Run a spaced-repetition system for your knowledge.'], examples: ['A knowledge base you actually review.'], next: 'Master a field.', claim: 'you retain knowledge long-term with a system.' },
      { level: 50, title: 'Master a Field', meaning: 'Reach deep expertise in one field through sustained, structured learning.', why: 'Depth compounds into real capability and opportunity.', doThis: ['Go deep in one field over months.'], examples: ['Genuine expertise in one area.'], next: 'Polymath.', claim: 'you have deep expertise in one field.' },
      { level: 75, title: 'Cross-Domain', meaning: 'Learn across fields and connect ideas (mental models, first principles).', why: 'Connecting fields is where real insight and creativity come from.', doThis: ['Study several fields; connect their ideas.'], examples: ['An insight from connecting two fields.'], next: 'Mastery.', claim: 'you learn across fields and connect ideas.' },
      { level: 100, title: 'Mastery', meaning: 'Learn anything efficiently; think in first principles; never stop growing.', why: 'The top: a self-directed lifelong learner.', doThis: ['Keep a lifelong learning practice.'], examples: ['A track record of learning anything.'], next: 'Keep learning.', claim: 'you can learn anything efficiently and think from first principles.' },
    ],
    reading: [
      { level: 1, title: 'The Habit', meaning: 'Read a little every day \u2014 build a consistent daily reading habit (even 10 pages).', why: 'Consistency beats intensity; a daily habit compounds into hundreds of books.', doThis: ['Read 10+ pages every day; keep a book with you.'], examples: ['A 7-day reading streak.'], next: 'Finish books.', claim: 'you read most days as a habit.' },
      { level: 3, title: 'Finish Books', meaning: 'Finish books you start; pick books you actually enjoy.', why: 'Finishing builds momentum; enjoyment sustains the habit.', doThis: ['Finish 3 books you enjoy; drop ones you don\u2019t.'], examples: ['3 finished books.'], next: 'Read faster.', claim: 'you consistently finish the books you start.' },
      { level: 6, title: 'Read Faster', meaning: 'Improve reading speed and comprehension (subvocalisation, chunking).', why: 'Faster reading with good comprehension means more books, more knowledge.', doThis: ['Practise reading in chunks; time your pages.'], examples: ['Noticeably faster with good comprehension.'], next: 'Retain what you read.', claim: 'you read faster while keeping comprehension.' },
      { level: 10, title: 'Retain & Apply', meaning: 'Take notes/highlights and apply ideas from what you read.', why: 'Reading you don\u2019t retain or apply is entertainment, not growth.', doThis: ['Note key ideas; apply one idea per book.'], examples: ['An idea from a book you actually used.'], next: 'Read widely.', claim: 'you retain and apply ideas from your reading.' },
      { level: 18, title: 'Read Widely', meaning: 'Read across genres and difficulty (fiction, non-fiction, harder texts).', why: 'Range builds knowledge, empathy and better thinking.', doThis: ['Read across 4+ genres this year.'], examples: ['A varied reading list.'], next: 'Volume.', claim: 'you read widely across genres.' },
      { level: 30, title: 'Volume Reader', meaning: 'Read 20+ books a year consistently.', why: 'Volume compounds into deep, broad knowledge.', doThis: ['Hit a yearly book target you set.'], examples: ['20+ books in a year.'], next: 'Deep reading.', claim: 'you read 20+ books a year.' },
      { level: 50, title: 'Deep Reading', meaning: 'Read and truly understand difficult/classic works; analyse and discuss them.', why: 'Deep reading of hard texts builds real intellectual depth.', doThis: ['Read a challenging classic and discuss it.'], examples: ['A tough classic you understood.'], next: 'Mastery.', claim: 'you can deeply read and analyse difficult works.' },
      { level: 75, title: 'Well-Read', meaning: 'A broad, deep base across the great books and your fields of interest.', why: 'Being well-read enriches thinking and conversation for life.', doThis: ['Work through key books in your fields + classics.'], examples: ['A well-rounded library read.'], next: 'Mastery.', claim: 'you have a broad, deep reading base.' },
      { level: 100, title: 'Mastery', meaning: 'A lifelong, wide and deep reader who learns and grows through books.', why: 'The top: books are a lifelong engine of growth.', doThis: ['Keep reading widely and deeply for life.'], examples: ['A lifelong reading practice.'], next: 'Never stop.', claim: 'you are a lifelong wide-and-deep reader.' },
    ],
  };

  window.OPTIONAL_QUESTS = {
    piano: [
      { lvl: 2,  title: 'Learn: Twinkle Twinkle',        desc: 'A first full melody.',              xp: 30 },
      { lvl: 4,  title: 'Learn: Ode to Joy (two hands)', desc: 'Melody + bass together.',           xp: 40 },
      { lvl: 6,  title: 'Learn: Happy Birthday',         desc: 'Play it for someone, any key.',     xp: 40 },
      { lvl: 9,  title: 'Learn: F\u00fcr Elise (theme)',    desc: 'The famous opening.',               xp: 60 },
      { lvl: 13, title: 'Learn a 4-chord pop song',      desc: 'Your choice \u2014 C-G-Am-F.',          xp: 60 },
      { lvl: 17, title: 'Learn: River Flows in You',     desc: 'Yiruma modern classic.',            xp: 80 },
      { lvl: 20, title: 'Sight-read 5 new pieces',       desc: 'Cold-read 5 grade-1/2 pieces.',     xp: 80 },
      { lvl: 24, title: 'Learn: Clocks (Coldplay)',      desc: 'Arpeggiated pop.',                  xp: 100 },
      { lvl: 30, title: 'Learn: F\u00fcr Elise (full)',     desc: 'The whole piece.',                  xp: 120 },
      { lvl: 36, title: 'Learn: Comptine (Am\u00e9lie)',    desc: 'Yann Tiersen theme.',               xp: 150 },
      { lvl: 45, title: 'Learn: a Bach Invention',       desc: 'Two-part counterpoint.',            xp: 200 },
      { lvl: 55, title: 'Learn: a Chopin Waltz',         desc: 'e.g. A minor.',                     xp: 250 },
      { lvl: 70, title: 'Learn: Nocturne Op.9 No.2',     desc: 'Chopin.',                           xp: 350 },
      { lvl: 85, title: 'Learn: Clair de Lune',          desc: 'Debussy.',                          xp: 500 },
      { lvl: 100,title: 'Learn: a Chopin Ballade',       desc: 'Concert showpiece.',                xp: 800 },
    ],
    drawing: [
      { lvl: 3,  title: 'Draw 10 everyday objects',  desc: 'Cup, key, shoe\u2026 from life.',       xp: 40 },
      { lvl: 10, title: 'Master study',              desc: 'Copy a drawing you admire.',        xp: 80 },
      { lvl: 15, title: 'Draw your room in perspective', desc: '2-point perspective.',           xp: 100 },
      { lvl: 22, title: '30 gesture drawings',        desc: 'One session, 30 poses.',            xp: 120 },
      { lvl: 45, title: 'Finish one full illustration', desc: 'Thumbnail to render.',            xp: 200 },
      { lvl: 70, title: 'Inktober / 30-day challenge', desc: 'One drawing a day for a month.',   xp: 400 },
    ],
    coding: [
      { lvl: 3,  title: 'Build FizzBuzz',            desc: 'Classic first challenge.',          xp: 40 },
      { lvl: 10, title: 'Build a to-do app',         desc: 'CLI or simple UI.',                 xp: 100 },
      { lvl: 15, title: 'Put a project on GitHub',   desc: 'With a clean README.',              xp: 100 },
      { lvl: 22, title: 'Deploy a website',          desc: 'Live on the internet.',             xp: 150 },
      { lvl: 32, title: 'Build an API-powered app',  desc: 'Fetch + store data.',               xp: 250 },
      { lvl: 70, title: 'Ship a product with users', desc: 'Real people use it.',               xp: 500 },
    ],
    tennis: [
      { lvl: 3,  title: '10-shot forehand rally',    desc: 'Keep it in 10x.',                   xp: 40 },
      { lvl: 10, title: 'Serve 7/10 in',             desc: 'First-serve consistency.',          xp: 100 },
      { lvl: 22, title: 'Win a practice set',        desc: 'Through consistency.',              xp: 150 },
      { lvl: 45, title: 'Join a club ladder',        desc: 'Play ranked matches.',              xp: 250 },
      { lvl: 70, title: 'Win a club tournament match', desc: 'Competitive win.',                xp: 400 },
    ],
    languages: [
      { lvl: 3,  title: 'Learn 100 core words',   desc: 'Flashcards.',                 xp: 50 },
      { lvl: 6,  title: 'First real conversation', desc: 'With a native speaker.',      xp: 120 },
      { lvl: 18, title: 'Watch a show, low subs', desc: 'One episode.',                xp: 150 },
      { lvl: 50, title: 'Finish a novel',         desc: 'In the language.',            xp: 400 },
    ],
    cooking: [
      { lvl: 3,  title: 'Cook 5 meals no recipe', desc: 'From memory.',               xp: 80 },
      { lvl: 18, title: 'Improvise a dinner',     desc: 'From the fridge.',            xp: 150 },
      { lvl: 30, title: 'Host a 3-course dinner', desc: 'Timed right.',               xp: 250 },
      { lvl: 50, title: 'Bake bread from scratch', desc: 'No bread machine.',          xp: 200 },
    ],
    calisthenics: [
      { lvl: 6,  title: 'First pull-up',          desc: 'Then build to 5.',           xp: 120 },
      { lvl: 30, title: 'Wall handstand 20s',     desc: 'Hold it.',                   xp: 200 },
      { lvl: 45, title: 'First muscle-up',        desc: 'Clean rep.',                 xp: 350 },
      { lvl: 60, title: 'Freestanding handstand', desc: '10s+.',                      xp: 400 },
    ],
    core: [
      { lvl: 6,  title: 'Hollow hold 30s',        desc: 'No sagging.',                xp: 60 },
      { lvl: 18, title: 'L-sit 10s',              desc: 'Full L-sit.',                xp: 150 },
      { lvl: 30, title: 'Dragon-flag negative',   desc: 'Slow and controlled.',       xp: 250 },
    ],
    strength: [
      { lvl: 10, title: 'Bench bodyweight',       desc: '1x BW for reps.',            xp: 200 },
      { lvl: 6,  title: 'Log 4 weeks straight',   desc: 'Every session.',             xp: 100 },
      { lvl: 30, title: 'Bench 1.25x BW',         desc: 'Advanced press.',            xp: 350 },
    ],
    dancing: [
      { lvl: 6,  title: 'Learn a 16-count combo', desc: 'Perform it clean.',          xp: 80 },
      { lvl: 18, title: 'Freestyle 1 minute',     desc: 'No freezing.',               xp: 150 },
      { lvl: 30, title: 'Perform a full routine', desc: 'Full song.',                 xp: 250 },
    ],
    sales: [
      { lvl: 3,  title: 'Start 3 convos/day',     desc: 'For a week.',                xp: 60 },
      { lvl: 18, title: 'Ask for the close',      desc: 'On a real lead.',            xp: 150 },
      { lvl: 30, title: 'Close 5 sales',          desc: 'Track them.',                xp: 250 },
    ],
    marketing: [
      { lvl: 6,  title: 'Post 30 days straight',  desc: 'One channel.',               xp: 120 },
      { lvl: 18, title: 'Build a lead magnet',    desc: 'Funnel + email.',            xp: 200 },
      { lvl: 50, title: 'Run a profitable ad',    desc: 'Positive ROI.',              xp: 350 },
    ],
    ai_tools: [
      { lvl: 3,  title: 'Master a prompt',        desc: 'Reliable output.',           xp: 60 },
      { lvl: 30, title: 'Build an AI tool',       desc: 'Small but real.',            xp: 250 },
      { lvl: 50, title: 'Build a RAG/agent flow', desc: 'Advanced.',                  xp: 400 },
    ],
    content: [
      { lvl: 6,  title: 'Post 30 days straight',  desc: 'Any platform.',              xp: 120 },
      { lvl: 18, title: 'Reach 1k followers',     desc: 'First real audience.',       xp: 250 },
      { lvl: 50, title: 'Earn from content',      desc: 'First income.',              xp: 400 },
    ],
    learning: [
      { lvl: 10, title: 'Learn a topic zero-to-solid', desc: 'With a plan.',          xp: 120 },
      { lvl: 18, title: 'Teach it to someone',    desc: 'Feynman technique.',         xp: 150 },
      { lvl: 50, title: 'Reach expertise in a field', desc: 'Real depth.',            xp: 400 },
    ],
    reading: [
      { lvl: 3,  title: 'Finish 3 books',         desc: 'You enjoy.',                 xp: 80 },
      { lvl: 30, title: 'Read 20 books in a year', desc: 'Volume.',                   xp: 300 },
      { lvl: 50, title: 'Read a hard classic',    desc: 'And understand it.',         xp: 250 },
    ],
  };
})();
