// =============================================================
// Gamenfy — Tiered skill ladders (v10.17)
// Unified quest + unlock path. TIER = LEVEL: claiming a tier
// brings the skill to that level. Each tier is an info tree:
// meaning / why / doThis / examples / next / claim (measurable).
// Piano + Puzzling are the reviewed templates; the same shape
// rolls out to every skill once approved.
// =============================================================
(function () {
  'use strict';
  window.SKILL_LADDERS = {
    piano: [
      { level: 1, title: 'First Contact',
        meaning: 'Learn the keyboard: find middle C, name the white keys (C D E F G A B), and see the octave pattern repeat. Sit with good posture — bench height so your forearms are level, relaxed wrists, curved hands.',
        why: 'Posture and hand shape are the foundation of everything — bad habits here cost months to unlearn and cause strain.',
        doThis: ['Play each white key up an octave and say its name out loud.', 'Find every C (just left of the group of 2 black keys).'],
        examples: ['Point out all the C\u2019s.', 'Recognise the 2-then-3 black-key pattern.'],
        next: 'Put 5 fingers on C-D-E-F-G.',
        claim: 'you can name any white key without looking and find middle C.' },
      { level: 2, title: 'Five-Finger Hand',
        meaning: 'Play a 5-finger pattern (C D E F G) with each hand separately, one finger per key, evenly.',
        why: 'Independent, even fingers are the core motor skill \u2014 this trains the brain to control each finger on its own.',
        doThis: ['Right hand thumb=C \u2026 pinky=G, slow, even tone, up and down.', 'Then the same with the left hand.'],
        examples: ['\u201cOde to Joy\u201d melody in C position.', '\u201cHot Cross Buns\u201d.'],
        next: 'Combine the hands slowly.',
        claim: 'you play a simple melody smoothly and evenly with one hand.' },
      { level: 4, title: 'Hands Together (simple)',
        meaning: 'Play a simple piece with both hands at once (melody in the right, held/simple bass in the left).',
        why: 'Coordinating two hands is the first big leap \u2014 your brain learns to split attention. Master each hand alone first, then combine at 50% tempo.',
        doThis: ['Learn each hand separately, then combine very slowly, counting out loud.'],
        examples: ['\u201cOde to Joy\u201d with left-hand root notes.'],
        next: 'Learn your first scale.',
        claim: 'you play one simple piece hands-together without mistakes.' },
      { level: 6, title: 'C Major Scale',
        meaning: 'C major scale, one octave, hands separately, using the thumb-under technique (fingering 1-2-3-1-2-3-4-5).',
        why: 'Scales train fingering, evenness and the thumb-cross that unlocks every key.',
        doThis: ['Slow, watch the thumb tuck under after E. Up and down.'],
        examples: ['C scale, then G scale.'],
        next: 'Scale hands together.',
        claim: 'you play the C scale one octave smoothly with correct fingering.' },
      { level: 9, title: 'Scale Together + First Real Piece',
        meaning: 'C scale two octaves hands together, and a beginner classical piece start to finish (e.g. a minuet from the Anna Magdalena Bach book).',
        why: 'Finishing a whole piece trains persistence, structure and musicality \u2014 not just technique.',
        doThis: ['Piece in 4-bar chunks; hand-by-hand; then together, slowly building up.'],
        examples: ['Petzold Minuet in G.', '\u201cF\u00fcr Elise\u201d (first theme).'],
        next: 'Learn chords.',
        claim: 'you can play one beginner piece all the way through.' },
      { level: 13, title: 'Chords & Accompaniment',
        meaning: 'Major/minor triads; I-IV-V-I in C and G; play a song with chord accompaniment (left-hand chords, right-hand melody or singing).',
        why: 'Chords let you play thousands of pop songs \u2014 this opens up \u201cjust making music\u201d.',
        doThis: ['Learn the shape of major/minor triads; practise switching C-F-G chords smoothly.'],
        examples: ['A 4-chord song (C-G-Am-F).'],
        next: 'Learn to sight-read.',
        claim: 'you can accompany a song with I-IV-V chords.' },
      { level: 17, title: 'Song Repertoire',
        meaning: 'Learn 3 full songs you enjoy, by heart (chords + melody). Build a set you can play any time.',
        why: 'Repertoire keeps it fun and cements everything — playing for real is the best practice.',
        doThis: ['Pick 3 songs you love; learn them fully; keep them polished.'],
        examples: ['A pop song, a film theme, and a short classical piece.'],
        next: 'Sight-reading.',
        claim: 'you can play 3 full songs from memory.' },
      { level: 20, title: 'Sight-Reading & Rhythm',
        meaning: 'Read simple sheet music at sight (grade 1-2) and count rhythms (quarters/eighths) correctly.',
        why: 'Sight-reading makes you independent \u2014 you can pick up any piece without a tutorial.',
        doThis: ['5 min a day sight-reading a new simple piece; count out loud.'],
        examples: ['Grade-1 pieces at sight.'],
        next: 'Hand independence + dynamics.',
        claim: 'you can read an unfamiliar grade-1/2 piece reasonably at sight.' },
      { level: 24, title: 'Two-Hand Independence',
        meaning: 'Pieces where the hands play genuinely different rhythms (a waltz: left hand oom-pah-pah, right hand a flowing melody).',
        why: 'True independence between the hands is what separates beginners from intermediates.',
        doThis: ['Practise a waltz or a broken-chord left hand under a singing right-hand melody.'],
        examples: ['A simple waltz; \u201cRiver Flows in You\u201d.'],
        next: 'Independence, dynamics & pedal.',
        claim: 'you play a piece with clearly independent hand rhythms.' },
      { level: 30, title: 'Independence, Dynamics & Pedal',
        meaning: 'Hands playing different rhythms; playing with dynamics (soft/loud); basic pedal use. An intermediate piece.',
        why: 'Musicality (dynamics, pedal) lifts it from \u201cnotes\u201d to \u201cmusic\u201d.',
        doThis: ['Practise a piece with marked dynamics; add pedal on chord changes.'],
        examples: ['Full \u201cF\u00fcr Elise\u201d; a Clementi sonatina.'],
        next: 'Polish an intermediate piece.',
        claim: 'you play an intermediate piece with dynamics and pedal.' },
      { level: 36, title: 'Phrasing & Half-Pedal',
        meaning: 'Musical phrasing (shaping lines), half-pedalling, and voicing the melody above the accompaniment.',
        why: 'This is where playing becomes expressive and personal, not mechanical.',
        doThis: ['Take a lyrical piece; shape each phrase; practise half-pedal changes.'],
        examples: ['\u201cComptine d\u2019un autre \u00e9t\u00e9\u201d (Am\u00e9lie).'],
        next: 'Intermediate repertoire.',
        claim: 'you play a lyrical piece with real phrasing and pedal control.' },
      { level: 45, title: 'Intermediate Repertoire',
        meaning: 'A full intermediate piece to performance level (e.g. a Chopin prelude or a Bach Invention). All 12 major scales fluent.',
        why: 'Real repertoire + all keys is the mark of a solid intermediate pianist.',
        doThis: ['Pick one intermediate piece and polish it fully; drill all 12 major scales.'],
        examples: ['Bach Invention No. 1; Chopin Prelude in E minor.'],
        next: 'Advanced technique.',
        claim: 'you perform one intermediate piece at level.' },
      { level: 55, title: 'Advanced Intermediate',
        meaning: 'A harder piece (a Chopin waltz or a Debussy miniature) and faster scales/arpeggios in all keys.',
        why: 'Bridges the gap to advanced repertoire.',
        doThis: ['Learn one advanced-intermediate piece; speed up scales in all 12 keys.'],
        examples: ['Chopin Waltz in A minor; Debussy \u201cArabesque\u201d.'],
        next: 'Advanced technique.',
        claim: 'you play an advanced-intermediate piece cleanly.' },
      { level: 70, title: 'Advanced Technique',
        meaning: 'Arpeggios, fast passages, a Chopin nocturne or a Bach fugue.',
        why: 'Advanced technique opens the great repertoire.',
        doThis: ['Daily arpeggio + fast-passage drills; learn one advanced piece.'],
        examples: ['Chopin Nocturne Op. 9 No. 2.'],
        next: 'Mastery.',
        claim: 'you can play an advanced piece.' },
      { level: 85, title: 'Concert Piece',
        meaning: 'A demanding concert-level piece, polished to performance standard.',
        why: 'Performance-ready advanced repertoire is the doorway to mastery.',
        doThis: ['Choose one concert piece and refine it over months to performance level.'],
        examples: ['Debussy \u201cClair de Lune\u201d; a Chopin Ballade excerpt.'],
        next: 'Mastery.',
        claim: 'you perform a concert-level piece.' },
      { level: 100, title: 'Mastery',
        meaning: 'Perform an advanced piece from memory; improvise or accompany by ear.',
        why: 'The final tier: technique + musicianship + freedom.',
        doThis: ['Perform from memory; practise playing along by ear.'],
        examples: ['Perform a full advanced piece; jam along to a song by ear.'],
        next: 'You\u2019ve reached the top \u2014 keep the fire.',
        claim: 'you perform at level and can play by ear.' },
    ],
    puzzling: [
      { level: 1, title: 'First Puzzle',
        meaning: 'Finish a small jigsaw (100-300 pieces). Core method: turn all pieces face-up, find the edge pieces, build the frame.',
        why: 'The border gives you the boundary; sorting before you start is the fundamental skill.',
        doThis: ['Flip all pieces face-up \u2192 separate edges \u2192 build the frame \u2192 fill in.'],
        examples: ['A 300-piece landscape.'],
        next: 'Sort by colour/pattern.',
        claim: 'you finish a 100-300 piece puzzle.' },
      { level: 2, title: 'Sort & Section',
        meaning: 'Finish a 500-piece puzzle by sorting into colour/pattern groups.',
        why: 'Sorting into sections turns chaos into solvable chunks.',
        doThis: ['Group by colour/distinct features \u2192 build recognisable areas \u2192 connect them.'],
        examples: ['A 500-piece image with clear colour blocks.'],
        next: 'The standard 1000.',
        claim: 'you finish a 500-piece puzzle using the sorting method.' },
      { level: 4, title: '1000 Pieces',
        meaning: 'Finish a standard 1000-piece puzzle.',
        why: 'The \u201cstandard\u201d adult puzzle \u2014 a real milestone.',
        doThis: ['Frame \u2192 colour sections \u2192 tricky uniform areas (sky/water) by piece shape.'],
        examples: ['A 1000-piece scene.'],
        next: 'Beat the clock / uniform areas.',
        claim: 'you finish a 1000-piece puzzle.' },
      { level: 6, title: 'Beat the Clock / Uniform Areas',
        meaning: 'Finish a 1000-piece puzzle under your personal best, or one with large uniform areas (sky/sea).',
        why: 'Uniform areas force you to solve by piece shape instead of image \u2014 an advanced skill.',
        doThis: ['Time yourself; or pick a puzzle with a big plain area and solve it by shape.'],
        examples: ['A mostly-sky landscape.'],
        next: '2000 pieces.',
        claim: 'you finish a uniform-area puzzle or beat your 1000 time.' },
      { level: 9, title: '2000 Pieces',
        meaning: 'Finish a 2000-piece puzzle.',
        why: 'More volume = more sorting and memory discipline.',
        doThis: ['Sort into many trays; work section by section over multiple sessions.'],
        examples: ['A 2000-piece detailed image.'],
        next: 'Hard modes.',
        claim: 'you finish a 2000-piece puzzle.' },
      { level: 14, title: 'Hard Modes',
        meaning: 'All-white/gradient puzzles, or shaped/3D puzzles.',
        why: 'With no image you solve purely on shape \u2014 the hardest puzzle thinking.',
        doThis: ['Try an \u201cimpossible\u201d white/gradient puzzle; solve by edge shape alone.'],
        examples: ['A pure-white or gradient puzzle.'],
        next: '5000 pieces / speed.',
        claim: 'you finish a white/gradient \u201cimpossible\u201d puzzle.' },
      { level: 22, title: '5000 Pieces / Speed',
        meaning: 'Finish a 5000-piece puzzle, or reach competitive speed on 1000.',
        why: 'Scale + speed is elite territory.',
        doThis: ['Commit to a 5000 over several weeks, or time-train 1000s.'],
        examples: ['A 5000-piece panorama.'],
        next: 'Master builder.',
        claim: 'you finish a 5000-piece puzzle.' },
      { level: 40, title: 'Master Builder',
        meaning: 'A 10,000+ piece puzzle, or consistent competition times.',
        why: 'Only the dedicated get here.',
        doThis: ['Take on a 10k over a long stretch, or enter a speed event.'],
        examples: ['A 10,000-piece world map.'],
        next: 'Legend.',
        claim: 'you finish a 10,000-piece puzzle.' },
      { level: 100, title: 'Puzzle Legend',
        meaning: 'Multiple 10k+ puzzles, or a podium at a speed-puzzling competition.',
        why: 'The top of the craft.',
        doThis: ['Build a collection of giant puzzles, or compete.'],
        examples: ['Podium at a speed-puzzling event.'],
        next: 'You\u2019ve mastered it.',
        claim: 'you puzzle at competition level.' },
    ],
    drawing: [
      { level: 1, title: 'Marks & Lines', meaning: 'Make controlled marks: straight lines, curves, circles and ovals, drawn from the shoulder/elbow \u2014 not just the wrist.', why: 'Line control is the alphabet of drawing; loose confident lines beat stiff scratchy ones.', doThis: ['Fill a page with lines, then circles/ovals, each in one smooth stroke.'], examples: ['A page of clean circles and parallel lines.'], next: 'Turn shapes into 3D forms.', claim: 'you can draw a smooth straight line and a round circle on demand.' },
      { level: 3, title: 'Shapes to Forms', meaning: 'Turn flat shapes into 3D forms: cube, sphere, cylinder, cone.', why: 'Every object is built from these forms; seeing them lets you draw anything.', doThis: ['Draw each form from a few angles; add a light source and one cast shadow.'], examples: ['A shaded sphere and cube.'], next: 'Proportion & measuring.', claim: 'you can draw the four basic forms with simple shading.' },
      { level: 6, title: 'Proportion & Measuring', meaning: 'Copy a real object with correct proportions using measuring (comparing sizes/angles).', why: 'Accurate proportion is what makes a drawing \u201clook right\u201d.', doThis: ['Draw a still life (mug, bottle) by measuring relationships, not guessing.'], examples: ['A believable still life of 2-3 objects.'], next: 'Light & shading.', claim: 'you can draw a still life with believable proportions.' },
      { level: 10, title: 'Value & Shading', meaning: 'Render light and shadow with a full value range (highlight \u2192 core shadow \u2192 reflected light \u2192 cast shadow).', why: 'Value creates the illusion of 3D and mood \u2014 more than line does.', doThis: ['Shade a sphere and a still life with 5+ values; squint to see big shapes.'], examples: ['A convincingly 3D shaded still life.'], next: 'Perspective.', claim: 'you can shade an object with a smooth, believable value range.' },
      { level: 15, title: '1 & 2-Point Perspective', meaning: 'Draw boxes, rooms and streets in 1- and 2-point perspective with a horizon line and vanishing points.', why: 'Perspective lets you draw believable space and architecture.', doThis: ['Draw a room interior and a street in 2-point perspective.'], examples: ['A believable room in perspective.'], next: 'Gesture & the figure.', claim: 'you can draw a box and a simple room in correct perspective.' },
      { level: 22, title: 'Gesture & Figure Basics', meaning: 'Capture a pose in 30-60s gesture drawings; build the figure from simple forms and proportion (heads-tall).', why: 'The figure is the hardest, most rewarding subject; gesture keeps it alive.', doThis: ['Do 20 quick gesture sketches; then one longer figure using the 7.5-heads proportion.'], examples: ['A page of lively gesture poses.'], next: 'Anatomy & construction.', claim: 'you can capture a believable pose and basic figure proportions.' },
      { level: 32, title: 'Anatomy & Construction', meaning: 'Learn the major muscle/bone landmarks and construct heads and hands.', why: 'Anatomy turns stick-figures into believable people.', doThis: ['Study and draw the skull, torso and hand from reference.'], examples: ['A constructed head from multiple angles.'], next: 'Composition & your style.', claim: 'you can construct a head and hand from imagination.' },
      { level: 45, title: 'Composition & Rendering', meaning: 'Compose a full finished piece (thumbnails \u2192 value study \u2192 render) with strong focal point and design.', why: 'Composition is what separates a study from a picture people stop to look at.', doThis: ['Take one idea from thumbnail to a fully rendered finished drawing.'], examples: ['A finished, composed illustration.'], next: 'Personal voice.', claim: 'you can take an idea to a finished, well-composed drawing.' },
      { level: 70, title: 'Style & Speed', meaning: 'Develop a recognisable personal style; draw fluently and quickly from imagination.', why: 'A voice + speed is what makes an artist, not just a copier.', doThis: ['Do a daily drawing from imagination in your own style for a month.'], examples: ['A cohesive set of pieces in your style.'], next: 'Mastery.', claim: 'you draw fluently from imagination in a recognisable style.' },
      { level: 100, title: 'Mastery', meaning: 'Produce portfolio-level work; draw anything you can imagine.', why: 'The top: technique, imagination and voice united.', doThis: ['Build a portfolio; take commissions or share work publicly.'], examples: ['A portfolio others recognise as yours.'], next: 'Keep creating.', claim: 'you can draw anything convincingly, in your own voice.' },
    ],
    coding: [
      { level: 1, title: 'First Program', meaning: 'Write and run your first program (print output, a variable, basic math) in one language (Python recommended).', why: 'Everything starts with being able to run code and see a result.', doThis: ['Install Python; write a script that prints and does arithmetic; run it.'], examples: ['A script that greets you and adds two numbers.'], next: 'Logic & control flow.', claim: 'you can write and run a small script from scratch.' },
      { level: 3, title: 'Logic & Control Flow', meaning: 'Use variables, if/else, loops (for/while) and basic data types to solve small problems.', why: 'Control flow is how programs make decisions and repeat work \u2014 the core of all code.', doThis: ['Solve 10 small exercises using loops and conditionals.'], examples: ['FizzBuzz; a number-guessing game.'], next: 'Functions & structure.', claim: 'you can solve FizzBuzz and a guessing game on your own.' },
      { level: 6, title: 'Functions & Data Structures', meaning: 'Write functions; use lists/arrays, dictionaries/maps; break a problem into pieces.', why: 'Functions + data structures let you build anything non-trivial without chaos.', doThis: ['Refactor a script into functions; use a dict to count word frequencies.'], examples: ['A word-counter using functions and a dictionary.'], next: 'A real small project.', claim: 'you can write clean functions and use lists/dicts to solve a problem.' },
      { level: 10, title: 'First Real Project', meaning: 'Build a small complete program end-to-end (e.g. a to-do CLI, a simple calculator, a text game).', why: 'Finishing a real project is where scattered skills become ability.', doThis: ['Pick one small app idea and build it fully, start to finish.'], examples: ['A working command-line to-do app.'], next: 'Version control & debugging.', claim: 'you built one small program that actually works.' },
      { level: 15, title: 'Git, Debugging & Reading Docs', meaning: 'Use Git (commit/branch/push), read error messages, use a debugger, and read documentation to solve problems.', why: 'These are the daily survival skills of every real developer.', doThis: ['Put a project on GitHub; fix a bug using the debugger; use a new library from its docs.'], examples: ['A project on GitHub with a clean commit history.'], next: 'Web basics.', claim: 'you use Git and can debug your own code with a debugger.' },
      { level: 22, title: 'Web / App Basics', meaning: 'Build a simple web page or app (HTML/CSS/JS, or a Python web app) that does something useful.', why: 'Shipping something others can use is a huge motivator and a real skill jump.', doThis: ['Build and deploy a simple site or app (like Gamenfy itself!).'], examples: ['A deployed personal site or small web tool.'], next: 'Data & APIs.', claim: 'you built and deployed a small web page or app.' },
      { level: 32, title: 'APIs, Databases & Async', meaning: 'Fetch data from an API, store data in a database, handle async operations.', why: 'Real apps talk to servers and remember data \u2014 this is the backbone.', doThis: ['Build an app that calls an API and saves results to a database.'], examples: ['An app pulling live data and storing it.'], next: 'Clean code & testing.', claim: 'you can build an app that uses an API and a database.' },
      { level: 45, title: 'Clean Code, Testing & Design', meaning: 'Write readable, tested, well-structured code; understand basic design patterns and algorithms/complexity.', why: 'The difference between code that works once and code you can grow.', doThis: ['Add tests to a project; refactor for readability; learn Big-O basics.'], examples: ['A tested, well-structured codebase.'], next: 'Build something people use.', claim: 'you write tested, readable, well-structured code.' },
      { level: 70, title: 'Ship Real Software', meaning: 'Build and ship a non-trivial product that real people use; handle scale, security and maintenance.', why: 'Shipping real software for users is the mark of a real engineer.', doThis: ['Launch a product/tool and maintain it with real users.'], examples: ['A live product with actual users.'], next: 'Mastery.', claim: 'you shipped software that real people use.' },
      { level: 100, title: 'Mastery', meaning: 'Architect complex systems; mentor others; work fluently across the stack.', why: 'The top: you can design, build and lead.', doThis: ['Architect a full system; help others level up.'], examples: ['A system you designed end-to-end.'], next: 'Keep building.', claim: 'you can architect and build complex systems fluently.' },
    ],
    tennis: [
      { level: 1, title: 'Grip & Ready', meaning: 'Learn the continental and eastern forehand grips, the ready position, and the split-step.', why: 'Grip and footwork basics decide everything that follows \u2014 wrong grip caps you fast.', doThis: ['Practise the ready position and split-step; hold each grip correctly.'], examples: ['Shadow-swing with the correct forehand grip.'], next: 'Rally the forehand.', claim: 'you can take the ready position and use the correct forehand grip.' },
      { level: 3, title: 'Forehand Rally', meaning: 'Hit a controlled forehand with a full swing (low-to-high) and keep a rally going.', why: 'The forehand is your main weapon; a reliable one is the foundation.', doThis: ['Rally forehands against a wall or partner, aiming for 10 in a row.'], examples: ['10 forehands in a row over the net.'], next: 'Backhand.', claim: 'you can rally 10 forehands in a row.' },
      { level: 6, title: 'Backhand', meaning: 'Hit a controlled backhand (one- or two-handed) and rally both wings.', why: 'A solid backhand means opponents can\u2019t just attack one side.', doThis: ['Rally backhands; then rally alternating forehand/backhand.'], examples: ['10 backhands in a row.'], next: 'Serve.', claim: 'you can rally 10 backhands in a row.' },
      { level: 10, title: 'The Serve', meaning: 'Develop a reliable serve: toss, trophy position, and a flat/slice serve that lands in.', why: 'The serve is the only shot fully in your control \u2014 and it starts every point.', doThis: ['Practise the toss; hit 20 serves, aiming for consistency in the box.'], examples: ['7/10 first serves in.'], next: 'Volleys & consistency.', claim: 'you land 7 of 10 serves in the box.' },
      { level: 15, title: 'Volleys & Net Play', meaning: 'Hit forehand and backhand volleys with a punch; approach and finish at the net.', why: 'Net skills let you finish points and add pressure.', doThis: ['Practise volleys; play approach-and-volley points.'], examples: ['Clean volleys off both wings.'], next: 'Play full points.', claim: 'you can volley off both wings and finish at the net.' },
      { level: 22, title: 'Consistency & Match Play', meaning: 'Play full sets, keep the ball in play under pressure, and win points through consistency.', why: 'At club level, whoever misses less wins \u2014 consistency beats power.', doThis: ['Play practice sets; track your unforced errors and reduce them.'], examples: ['Winning a set through fewer errors.'], next: 'Spin & placement.', claim: 'you can play a full set and win through consistency.' },
      { level: 32, title: 'Spin, Placement & Tactics', meaning: 'Use topspin/slice deliberately, place shots to corners, and play with a game plan.', why: 'Spin and placement turn rallies into weapons and expose opponents.', doThis: ['Hit with heavy topspin; play targets; build points with a plan.'], examples: ['Constructing a point to a winner.'], next: 'Compete.', claim: 'you can use spin and placement tactically in a match.' },
      { level: 45, title: 'Competitive Play', meaning: 'Compete in club matches/ladders; handle pressure, tactics and different opponents.', why: 'Real competition sharpens every part of your game.', doThis: ['Join a ladder or club competition; play ranked matches.'], examples: ['Wins against varied opponents.'], next: 'Advanced game.', claim: 'you compete and win in club-level matches.' },
      { level: 70, title: 'Advanced Game', meaning: 'All shots reliable under pressure; strong serve, movement and match IQ; win at a high club/regional level.', why: 'The complete player \u2014 few weaknesses left to exploit.', doThis: ['Train movement and serve+1 patterns; compete at a higher level.'], examples: ['Success at regional/high club level.'], next: 'Mastery.', claim: 'you win consistently at a high club level.' },
      { level: 100, title: 'Mastery', meaning: 'Tournament-level tennis: elite consistency, weapons, fitness and mentality.', why: 'The top of the amateur game.', doThis: ['Compete at tournament level; train like an athlete.'], examples: ['Tournament results.'], next: 'Keep competing.', claim: 'you play and win at tournament level.' },
    ],
  };

  window.OPTIONAL_QUESTS = {
    piano: [
      { lvl: 2,  title: 'Learn: Twinkle Twinkle',        desc: 'A first full melody.',              xp: 30 },
      { lvl: 4,  title: 'Learn: Ode to Joy (two hands)', desc: 'Melody + bass together.',           xp: 40 },
      { lvl: 6,  title: 'Learn: Happy Birthday',         desc: 'Play it for someone, any key.',     xp: 40 },
      { lvl: 9,  title: 'Learn: F\u00fcr Elise (theme)',    desc: 'The famous opening.',               xp: 60 },
      { lvl: 13, title: 'Learn a 4-chord pop song',      desc: 'Your choice \u2014 C-G-Am-F.',          xp: 60 },
      { lvl: 17, title: 'Learn: River Flows in You',     desc: 'Yiruma modern classic.',            xp: 80 },
      { lvl: 20, title: 'Sight-read 5 new pieces',       desc: 'Cold-read 5 grade-1/2 pieces.',     xp: 80 },
      { lvl: 24, title: 'Learn: Clocks (Coldplay)',      desc: 'Arpeggiated pop.',                  xp: 100 },
      { lvl: 30, title: 'Learn: F\u00fcr Elise (full)',     desc: 'The whole piece.',                  xp: 120 },
      { lvl: 36, title: 'Learn: Comptine (Am\u00e9lie)',    desc: 'Yann Tiersen theme.',               xp: 150 },
      { lvl: 45, title: 'Learn: a Bach Invention',       desc: 'Two-part counterpoint.',            xp: 200 },
      { lvl: 55, title: 'Learn: a Chopin Waltz',         desc: 'e.g. A minor.',                     xp: 250 },
      { lvl: 70, title: 'Learn: Nocturne Op.9 No.2',     desc: 'Chopin.',                           xp: 350 },
      { lvl: 85, title: 'Learn: Clair de Lune',          desc: 'Debussy.',                          xp: 500 },
      { lvl: 100,title: 'Learn: a Chopin Ballade',       desc: 'Concert showpiece.',                xp: 800 },
    ],
    drawing: [
      { lvl: 3,  title: 'Draw 10 everyday objects',  desc: 'Cup, key, shoe\u2026 from life.',       xp: 40 },
      { lvl: 10, title: 'Master study',              desc: 'Copy a drawing you admire.',        xp: 80 },
      { lvl: 15, title: 'Draw your room in perspective', desc: '2-point perspective.',           xp: 100 },
      { lvl: 22, title: '30 gesture drawings',        desc: 'One session, 30 poses.',            xp: 120 },
      { lvl: 45, title: 'Finish one full illustration', desc: 'Thumbnail to render.',            xp: 200 },
      { lvl: 70, title: 'Inktober / 30-day challenge', desc: 'One drawing a day for a month.',   xp: 400 },
    ],
    coding: [
      { lvl: 3,  title: 'Build FizzBuzz',            desc: 'Classic first challenge.',          xp: 40 },
      { lvl: 10, title: 'Build a to-do app',         desc: 'CLI or simple UI.',                 xp: 100 },
      { lvl: 15, title: 'Put a project on GitHub',   desc: 'With a clean README.',              xp: 100 },
      { lvl: 22, title: 'Deploy a website',          desc: 'Live on the internet.',             xp: 150 },
      { lvl: 32, title: 'Build an API-powered app',  desc: 'Fetch + store data.',               xp: 250 },
      { lvl: 70, title: 'Ship a product with users', desc: 'Real people use it.',               xp: 500 },
    ],
    tennis: [
      { lvl: 3,  title: '10-shot forehand rally',    desc: 'Keep it in 10x.',                   xp: 40 },
      { lvl: 10, title: 'Serve 7/10 in',             desc: 'First-serve consistency.',          xp: 100 },
      { lvl: 22, title: 'Win a practice set',        desc: 'Through consistency.',              xp: 150 },
      { lvl: 45, title: 'Join a club ladder',        desc: 'Play ranked matches.',              xp: 250 },
      { lvl: 70, title: 'Win a club tournament match', desc: 'Competitive win.',                xp: 400 },
    ],
  };
})();
