// =============================================================
// Gamenfy — Quest ladders per skill  (v4.6 — expanded)
// Quests are OPTIONAL level-gated challenges that make a skill fun.
// They unlock as your skill level rises. Completing one is a one-off
// win that also grants XP. Each: { lvl, title, desc, xp }.
//
// Design: dense early levels (1-10) so there's always a next step,
// then meaningful checkpoints all the way to 100. Concrete and
// realistic — "what do I actually do" is always obvious.
// =============================================================
(function () {
  'use strict';

  const QUESTS = {
    // ───────────── MONEY ─────────────
    saving: [
      { lvl: 1,  title: 'First €50 Saved',      desc: 'Set aside your first €50 on purpose.',                       xp: 40 },
      { lvl: 3,  title: 'Open a Savings Pot',   desc: 'Create a separate savings account or pot.',                  xp: 60 },
      { lvl: 5,  title: 'Auto-Transfer',        desc: 'Set up an automatic transfer on payday.',                    xp: 100 },
      { lvl: 8,  title: 'No-Spend Day',         desc: 'Get through a full day spending €0.',                        xp: 80 },
      { lvl: 12, title: 'One Week Buffer',      desc: 'Save one week of expenses.',                                 xp: 200 },
      { lvl: 20, title: 'One Month Buffer',     desc: 'Save one month of expenses.',                                xp: 350 },
      { lvl: 35, title: 'Emergency Fund',       desc: 'Build a 3-month emergency fund.',                            xp: 900 },
      { lvl: 50, title: 'Six Months Safe',      desc: '6 months of runway in the bank.',                            xp: 1600 },
      { lvl: 70, title: 'One Year Free',        desc: '12 months of expenses saved.',                               xp: 3000 },
      { lvl: 90, title: 'Savers Mindset',       desc: 'Save 30%+ of income for 6 straight months.',                 xp: 5000 },
    ],
    investing: [
      { lvl: 1,  title: 'Learn the Basics',     desc: 'Understand stocks vs funds vs ETFs.',                        xp: 40 },
      { lvl: 3,  title: 'First Position',       desc: 'Make your first investment, any size.',                      xp: 80 },
      { lvl: 6,  title: 'Index Fund',           desc: 'Buy into a broad index fund / ETF.',                         xp: 120 },
      { lvl: 10, title: 'Diversified',          desc: 'Hold 3+ different assets/funds.',                            xp: 250 },
      { lvl: 15, title: 'Auto-Invest',          desc: 'Set up an automatic monthly investment.',                    xp: 400 },
      { lvl: 25, title: 'Hold Through a Dip',   desc: 'Dont panic-sell during a market drop.',                      xp: 600 },
      { lvl: 40, title: '€5k Invested',         desc: 'Reach €5,000 in invested capital.',                          xp: 1200 },
      { lvl: 55, title: '€25k Invested',        desc: 'Reach €25,000 invested.',                                    xp: 2200 },
      { lvl: 75, title: 'Six Figures',          desc: 'Reach €100k invested.',                                      xp: 4000 },
      { lvl: 95, title: 'Financial Engine',     desc: 'Investments generate meaningful passive income.',            xp: 6000 },
    ],
    budgeting: [
      { lvl: 1,  title: 'Track One Day',        desc: 'Log every expense for 24 hours.',                            xp: 30 },
      { lvl: 3,  title: 'Track One Week',       desc: 'Log every expense for 7 days.',                              xp: 80 },
      { lvl: 6,  title: 'Know Your Burn',       desc: 'Calculate your average monthly spend.',                      xp: 120 },
      { lvl: 10, title: 'Monthly Budget',       desc: 'Run a full month on a written budget.',                      xp: 250 },
      { lvl: 15, title: 'Cut the Fat',          desc: 'Cancel 3 subscriptions you dont use.',                       xp: 300 },
      { lvl: 25, title: 'Zero-Based',           desc: 'Give every euro a job for a full month.',                    xp: 600 },
      { lvl: 40, title: '50/30/20',             desc: 'Hit a needs/wants/savings split for 3 months.',              xp: 1000 },
      { lvl: 60, title: 'Budget on Autopilot',  desc: 'Run 6 months without overspending.',                         xp: 2000 },
      { lvl: 85, title: 'Money Master',         desc: 'A full year fully on-budget.',                               xp: 4000 },
    ],
    net_worth: [
      { lvl: 1,  title: 'Know Your Number',     desc: 'Calculate your current net worth.',                          xp: 50 },
      { lvl: 5,  title: 'Track It Monthly',     desc: 'Log your net worth 3 months running.',                       xp: 120 },
      { lvl: 12, title: 'In the Black',         desc: 'Reach a positive net worth.',                                xp: 300 },
      { lvl: 25, title: 'First €10k',           desc: 'Cross €10k net worth.',                                      xp: 700 },
      { lvl: 40, title: '€25k Club',            desc: 'Cross €25k net worth.',                                      xp: 1200 },
      { lvl: 55, title: '€50k Club',            desc: 'Cross €50k net worth.',                                      xp: 2000 },
      { lvl: 75, title: 'Six Figures',          desc: 'Cross €100k net worth.',                                     xp: 3500 },
      { lvl: 90, title: 'Quarter Million',      desc: 'Cross €250k net worth.',                                     xp: 6000 },
      { lvl: 100,title: 'Millionaire',          desc: 'Cross €1,000,000 net worth.',                                xp: 12000 },
    ],

    // ───────────── BODY ─────────────
    tennis: [
      { lvl: 1,  title: 'First Rally',          desc: 'Hit 10 balls in a row against a wall.',                      xp: 40 },
      { lvl: 2,  title: 'Grip & Stance',        desc: 'Learn the proper forehand grip and ready position.',         xp: 50 },
      { lvl: 3,  title: 'Club Night',           desc: 'Show up to one social tennis evening at a club.',            xp: 80 },
      { lvl: 4,  title: 'Backhand Reps',        desc: 'Hit 20 backhands in a row against a wall.',                  xp: 90 },
      { lvl: 5,  title: 'Ball Machine Drill',   desc: 'Do a full 30-min ball-machine / cannon session.',            xp: 120 },
      { lvl: 7,  title: 'First Serve In',       desc: 'Land 10 first serves in the box.',                           xp: 150 },
      { lvl: 10, title: 'First Set',            desc: 'Play a full set against a real opponent.',                   xp: 250 },
      { lvl: 15, title: 'Win a Set',            desc: 'Win a full set against someone.',                            xp: 350 },
      { lvl: 20, title: 'Serve & Volley',       desc: 'Win 5 points in one match serve-and-volley.',                xp: 450 },
      { lvl: 30, title: 'Beat a Regular',       desc: 'Beat someone who plays weekly.',                             xp: 700 },
      { lvl: 40, title: 'Tournament Entry',     desc: 'Enter a local amateur tournament.',                          xp: 1000 },
      { lvl: 55, title: 'Ranked Player',        desc: 'Earn an official club / league ranking.',                    xp: 1800 },
      { lvl: 75, title: 'Tournament Win',       desc: 'Win a bracket at any sanctioned tournament.',                xp: 3000 },
      { lvl: 90, title: 'Club Champion',        desc: 'Win your club championship.',                                xp: 5000 },
    ],
    gym: [
      { lvl: 1,  title: 'Walk In',              desc: 'Complete your first logged workout.',                        xp: 40 },
      { lvl: 2,  title: 'Learn the Big 3',      desc: 'Practise squat, bench and deadlift form.',                   xp: 60 },
      { lvl: 3,  title: 'Three in a Week',      desc: 'Train 3 times in one week.',                                 xp: 100 },
      { lvl: 5,  title: 'Bodyweight Bench',     desc: 'Bench press your own bodyweight for 1 rep.',                 xp: 200 },
      { lvl: 7,  title: 'Two-Week Streak',      desc: 'Train consistently for 2 full weeks.',                       xp: 180 },
      { lvl: 10, title: 'Plate Club',           desc: 'Deadlift 100 kg.',                                           xp: 350 },
      { lvl: 15, title: 'Body Recomp',          desc: 'Notice your first visible muscle change.',                   xp: 300 },
      { lvl: 25, title: '1.5x Squat',           desc: 'Squat 1.5× bodyweight.',                                     xp: 700 },
      { lvl: 40, title: '2x Deadlift',          desc: 'Deadlift 2× bodyweight.',                                    xp: 1200 },
      { lvl: 50, title: 'Century Club',         desc: '100 logged workouts total.',                                 xp: 1600 },
      { lvl: 70, title: 'Three Plates',         desc: 'Deadlift 140 kg / squat 140 kg.',                            xp: 2800 },
      { lvl: 90, title: 'Iron Veteran',         desc: '500 logged workouts — a lifestyle, not a phase.',            xp: 5000 },
    ],
    calisthenics: [
      { lvl: 1,  title: 'First Pull-up',        desc: 'One clean dead-hang pull-up.',                               xp: 60 },
      { lvl: 2,  title: 'Ten Push-ups',         desc: '10 strict push-ups in a row.',                               xp: 60 },
      { lvl: 3,  title: 'Dead Hang',            desc: 'Hang from a bar for 30 seconds.',                            xp: 80 },
      { lvl: 5,  title: 'Dip Master',           desc: '10 strict parallel-bar dips.',                               xp: 150 },
      { lvl: 7,  title: 'Five Pull-ups',        desc: '5 strict pull-ups in a row.',                                xp: 180 },
      { lvl: 10, title: 'Pistol Squat',         desc: 'One full pistol squat each leg.',                            xp: 300 },
      { lvl: 15, title: 'Ten Pull-ups',         desc: '10 strict pull-ups in a row.',                               xp: 400 },
      { lvl: 20, title: 'Muscle-up',            desc: 'Your first bar muscle-up.',                                  xp: 600 },
      { lvl: 30, title: 'Pseudo Planche',       desc: 'Hold a pseudo-planche push-up position.',                    xp: 750 },
      { lvl: 35, title: 'Handstand Hold',       desc: 'Free-standing handstand for 10 seconds.',                    xp: 900 },
      { lvl: 50, title: 'L-sit to Handstand',   desc: 'Press from L-sit to handstand.',                             xp: 1400 },
      { lvl: 65, title: 'Front Lever',          desc: 'Hold a full front lever for 3 seconds.',                     xp: 2000 },
      { lvl: 80, title: 'Planche',              desc: 'Hold a full planche for 3 seconds.',                         xp: 3000 },
      { lvl: 95, title: 'One-Arm Pull-up',      desc: 'One clean one-arm pull-up.',                                 xp: 5000 },
    ],
    core: [
      { lvl: 1,  title: 'Plank Start',          desc: 'Hold a plank for 30 seconds.',                               xp: 40 },
      { lvl: 2,  title: 'Hollow Hold',          desc: 'Hold a hollow body for 20 seconds.',                         xp: 50 },
      { lvl: 4,  title: 'One-Minute Plank',     desc: 'Hold a plank for 60 seconds.',                               xp: 100 },
      { lvl: 6,  title: 'Two-Minute Plank',     desc: 'Hold a plank for 2 minutes.',                                xp: 180 },
      { lvl: 10, title: 'Hanging Knee Raises',  desc: '15 strict hanging knee raises.',                             xp: 300 },
      { lvl: 15, title: 'First Lines',          desc: 'Visible ab definition appears.',                             xp: 350 },
      { lvl: 25, title: 'Sixpack Visible',      desc: 'A clear sixpack at rest.',                                   xp: 600 },
      { lvl: 30, title: 'Toes to Bar',          desc: '10 toes-to-bar reps.',                                       xp: 750 },
      { lvl: 50, title: 'L-sit 30s',            desc: 'Hold an L-sit for 30 seconds.',                              xp: 1200 },
      { lvl: 65, title: 'Hanging Leg Raise',    desc: '10 straight-leg hanging raises.',                            xp: 1600 },
      { lvl: 80, title: 'Dragon Flag',          desc: 'One full dragon flag.',                                      xp: 2500 },
      { lvl: 95, title: 'Front Lever Raises',   desc: 'Core strong enough for front-lever raises.',                 xp: 4000 },
    ],
    stretching: [
      { lvl: 1,  title: 'Touch Your Toes',      desc: 'Reach your toes with straight legs.',                        xp: 40 },
      { lvl: 3,  title: 'Daily 5',              desc: 'Stretch 5 min a day for a week.',                            xp: 90 },
      { lvl: 6,  title: 'Forward Fold',         desc: 'Flat palms to floor in a forward fold.',                     xp: 120 },
      { lvl: 10, title: 'Deep Squat Hold',      desc: 'Sit in a flat-foot deep squat for 2 min.',                   xp: 250 },
      { lvl: 18, title: 'Shoulder Opener',      desc: 'Clasp hands behind back, both sides.',                       xp: 350 },
      { lvl: 25, title: 'Pancake Progress',     desc: 'Chest toward floor in a straddle pancake.',                  xp: 500 },
      { lvl: 40, title: 'Bridge Up',            desc: 'Push up into a full back bridge.',                           xp: 900 },
      { lvl: 60, title: 'Half Splits Flat',     desc: 'Both half-splits flat to the ground.',                       xp: 1400 },
      { lvl: 80, title: 'The Splits',           desc: 'Full front splits, both sides.',                             xp: 2200 },
      { lvl: 95, title: 'Middle Splits',        desc: 'Full straddle / middle splits.',                             xp: 3500 },
    ],
    recovery: [
      { lvl: 1,  title: 'First 5K',             desc: 'Run 5 km without stopping.',                                 xp: 100 },
      { lvl: 3,  title: 'Three Runs',           desc: 'Run 3 times in one week.',                                   xp: 120 },
      { lvl: 6,  title: 'Sub-30 5K',            desc: 'Run 5 km under 30 minutes.',                                 xp: 250 },
      { lvl: 12, title: '10K Club',             desc: 'Complete a 10 km run.',                                      xp: 450 },
      { lvl: 20, title: 'Sub-50 10K',           desc: 'Run 10 km under 50 minutes.',                                xp: 700 },
      { lvl: 35, title: 'Half Marathon',        desc: 'Finish a 21 km run.',                                        xp: 1300 },
      { lvl: 50, title: 'Sub-2h Half',          desc: 'Run a half marathon under 2 hours.',                         xp: 1800 },
      { lvl: 70, title: 'Marathon',             desc: 'Finish a full 42 km marathon.',                              xp: 3000 },
      { lvl: 90, title: 'Sub-4h Marathon',      desc: 'Run a marathon under 4 hours.',                              xp: 5000 },
    ],
    strength: [
      { lvl: 1,  title: 'Find Your Baseline',   desc: 'Log a 1-rep max for one big lift.',                          xp: 60 },
      { lvl: 3,  title: 'Progressive Overload', desc: 'Add weight to a lift two weeks running.',                    xp: 100 },
      { lvl: 6,  title: 'Bodyweight Squat x5',  desc: 'Squat your bodyweight for 5 reps.',                          xp: 180 },
      { lvl: 10, title: 'Bodyweight Bench',     desc: 'Bench press your bodyweight.',                               xp: 300 },
      { lvl: 18, title: 'Overhead Press',       desc: 'Strict overhead press 0.75× bodyweight.',                    xp: 500 },
      { lvl: 28, title: '1.25x Bench',          desc: 'Bench 1.25× bodyweight.',                                    xp: 800 },
      { lvl: 45, title: 'The 1000lb Club',      desc: 'Squat + bench + deadlift total of 450 kg.',                  xp: 1500 },
      { lvl: 65, title: 'Strong Total',         desc: 'Total of 550 kg across the big three.',                      xp: 2500 },
      { lvl: 85, title: 'Elite Total',          desc: 'Hit a powerlifting total you set as a stretch goal.',        xp: 4500 },
    ],

    // ───────────── MIND ─────────────
    reading: [
      { lvl: 1,  title: 'Open a Book',          desc: 'Read for 20 minutes today.',                                 xp: 40 },
      { lvl: 3,  title: 'A Week of Pages',      desc: 'Read every day for 7 days.',                                 xp: 90 },
      { lvl: 5,  title: 'First Finish',         desc: 'Finish one full book.',                                      xp: 200 },
      { lvl: 10, title: 'Three Books',          desc: 'Finish 3 books.',                                            xp: 350 },
      { lvl: 18, title: 'Five Shelf',           desc: 'Finish 5 books total.',                                      xp: 550 },
      { lvl: 30, title: 'Genre Hopper',         desc: 'Finish books in 4 different genres.',                        xp: 900 },
      { lvl: 45, title: 'Library of 25',        desc: 'Finish 25 books total.',                                     xp: 1600 },
      { lvl: 65, title: 'Fifty Deep',           desc: 'Finish 50 books total.',                                     xp: 2800 },
      { lvl: 90, title: 'The Hundred',          desc: 'Finish 100 books.',                                          xp: 5000 },
    ],
    focus: [
      { lvl: 1,  title: 'One Focus Block',      desc: 'A single 25-min phone-free focus block.',                    xp: 40 },
      { lvl: 3,  title: 'Three Blocks',         desc: '3 focus blocks in one day.',                                 xp: 100 },
      { lvl: 6,  title: 'Deep Hour',            desc: 'One uninterrupted 90-min deep work block.',                  xp: 200 },
      { lvl: 12, title: 'Flow Week',            desc: '5 deep blocks in one week.',                                 xp: 400 },
      { lvl: 20, title: 'Phone Away',           desc: 'A full work session with phone out of reach.',               xp: 350 },
      { lvl: 35, title: 'Deep Day',             desc: '4 hours of deep work in one day.',                           xp: 800 },
      { lvl: 55, title: 'Hundred Sessions',     desc: '100 logged deep work sessions.',                             xp: 1800 },
      { lvl: 80, title: 'Deep Master',          desc: 'Sustained deep work as a daily default.',                    xp: 3500 },
    ],
    journaling: [
      { lvl: 1,  title: 'First Entry',          desc: 'Write one journal entry today.',                             xp: 40 },
      { lvl: 3,  title: 'Three Days',           desc: 'Journal 3 days in a row.',                                   xp: 80 },
      { lvl: 7,  title: 'Seven Day Streak',     desc: 'Journal every day for a week.',                              xp: 200 },
      { lvl: 15, title: 'Month of Pages',       desc: '30 journal entries logged.',                                 xp: 500 },
      { lvl: 30, title: 'Morning Pages',        desc: '30 days of morning journaling.',                             xp: 900 },
      { lvl: 50, title: 'The Archive',          desc: '100 entries — a record of your growth.',                     xp: 1800 },
      { lvl: 75, title: 'A Year Written',       desc: '365 entries logged.',                                        xp: 4000 },
    ],

    // ───────────── BUSINESS ─────────────
    sales: [
      { lvl: 1,  title: 'First Pitch',          desc: 'Pitch an idea or product to one person.',                   xp: 60 },
      { lvl: 3,  title: 'Ten Pitches',          desc: 'Pitch to 10 people, any outcome.',                           xp: 150 },
      { lvl: 5,  title: 'First Yes',            desc: 'Close your first deal / sale.',                              xp: 300 },
      { lvl: 10, title: 'Five Closed',          desc: 'Close 5 deals.',                                             xp: 500 },
      { lvl: 18, title: 'Ten Closed',           desc: 'Close 10 deals total.',                                      xp: 800 },
      { lvl: 30, title: 'Handle the No',        desc: 'Turn a no into a yes through follow-up.',                    xp: 1000 },
      { lvl: 45, title: 'First €1k Deal',       desc: 'Close a single deal worth €1,000+.',                         xp: 1500 },
      { lvl: 65, title: 'Pipeline Pro',         desc: 'Keep a full pipeline for 3 months.',                         xp: 2500 },
      { lvl: 85, title: 'Rainmaker',            desc: 'Hit a personal revenue milestone you set.',                  xp: 4500 },
    ],
    marketing: [
      { lvl: 1,  title: 'First Post',           desc: 'Publish one piece of content publicly.',                     xp: 40 },
      { lvl: 3,  title: 'Five Posts',           desc: 'Publish 5 pieces of content.',                               xp: 100 },
      { lvl: 6,  title: 'Consistent Voice',     desc: 'Post 10 times on one channel.',                              xp: 250 },
      { lvl: 12, title: 'First 1k Views',       desc: 'Get a post past 1,000 views.',                               xp: 400 },
      { lvl: 20, title: '100 Followers',        desc: 'Reach 100 followers on one platform.',                       xp: 600 },
      { lvl: 35, title: 'First 10k Views',      desc: 'A post breaks 10,000 views.',                                xp: 1000 },
      { lvl: 50, title: '1,000 Followers',      desc: 'Reach 1,000 followers.',                                     xp: 1800 },
      { lvl: 75, title: '10k Audience',         desc: 'Reach 10,000 followers.',                                    xp: 3500 },
      { lvl: 95, title: 'Real Influence',       desc: 'A following that drives real results.',                      xp: 6000 },
    ],
    ai_tools: [
      { lvl: 1,  title: 'First Automation',     desc: 'Automate one repetitive task with AI.',                      xp: 60 },
      { lvl: 3,  title: 'Daily Driver',         desc: 'Use AI tools every day for a week.',                         xp: 120 },
      { lvl: 6,  title: 'Prompt Craft',         desc: 'Build a reusable prompt you rely on.',                       xp: 180 },
      { lvl: 12, title: 'Connect Two Tools',    desc: 'Make two tools talk to each other.',                         xp: 350 },
      { lvl: 20, title: 'Pipeline Builder',     desc: 'Chain tools into one automated pipeline.',                   xp: 600 },
      { lvl: 35, title: 'Save 3 Hours/Week',    desc: 'Automation saves you 3+ hrs weekly.',                        xp: 1000 },
      { lvl: 55, title: 'Agent Architect',      desc: 'Build an autonomous agent that does real work.',             xp: 2000 },
      { lvl: 80, title: 'AI-First',             desc: 'Your whole workflow is AI-native.',                          xp: 4000 },
    ],
    coding: [
      { lvl: 1,  title: 'Hello World',          desc: 'Write and run your first script.',                           xp: 60 },
      { lvl: 3,  title: 'Edit & Break',         desc: 'Change code, break it, fix it.',                             xp: 100 },
      { lvl: 6,  title: 'Ship a Page',          desc: 'Put a working site live (this dashboard counts!).',          xp: 250 },
      { lvl: 12, title: 'Connect an API',       desc: 'Fetch and display real data from an API.',                   xp: 450 },
      { lvl: 20, title: 'Add a Database',       desc: 'Build something with a database behind it.',                 xp: 700 },
      { lvl: 30, title: 'Squash Real Bugs',     desc: 'Debug and fix a tricky production issue.',                   xp: 900 },
      { lvl: 45, title: 'Full Stack',           desc: 'Build a complete front-to-back feature.',                    xp: 1500 },
      { lvl: 65, title: 'Ship a Product',       desc: 'Launch an app real people use.',                             xp: 2800 },
      { lvl: 90, title: 'Builder',              desc: 'Ship multiple products people pay for.',                     xp: 5500 },
    ],
    content: [
      { lvl: 1,  title: 'First Upload',         desc: 'Create and publish one video / reel / post.',                xp: 60 },
      { lvl: 3,  title: 'Five Pieces',          desc: 'Publish 5 pieces of content.',                               xp: 120 },
      { lvl: 7,  title: 'Ten Pieces',           desc: 'Publish 10 pieces of content.',                              xp: 300 },
      { lvl: 15, title: 'Find Your Format',     desc: 'Settle on a repeatable content format.',                     xp: 450 },
      { lvl: 25, title: 'First 10k Views',      desc: 'One piece breaks 10k views.',                                xp: 800 },
      { lvl: 40, title: 'Consistent Drops',     desc: 'Post on schedule for 2 months.',                             xp: 1200 },
      { lvl: 60, title: 'Creator',              desc: 'Build a real audience around your content.',                 xp: 2500 },
      { lvl: 85, title: 'Signature Style',      desc: 'A recognisable body of work.',                               xp: 4500 },
    ],

    // ───────────── LIFESTYLE ─────────────
    dating: [
      { lvl: 1,  title: 'Say Hi',               desc: 'Start a conversation with someone new.',                     xp: 40 },
      { lvl: 2,  title: 'Hold Eye Contact',     desc: 'Hold warm eye contact in a chat.',                           xp: 50 },
      { lvl: 3,  title: 'Social Reps',          desc: 'Go to a social event and meet people.',                      xp: 80 },
      { lvl: 5,  title: 'The Ask',              desc: 'Ask someone out (any outcome counts).',                      xp: 150 },
      { lvl: 7,  title: 'Three Conversations',  desc: 'Talk to 3 new people in one outing.',                        xp: 180 },
      { lvl: 10, title: 'Five Strangers',       desc: 'Genuinely talk to 5 new people in one night.',               xp: 300 },
      { lvl: 15, title: 'First Date',           desc: 'Go on a real planned date.',                                 xp: 450 },
      { lvl: 25, title: 'Second Date',          desc: 'Get to a second date with someone.',                         xp: 600 },
      { lvl: 40, title: 'Three Dates',          desc: 'See the same person for a 3rd date.',                        xp: 1000 },
      { lvl: 60, title: 'Something Real',       desc: 'Build a genuine connection.',                                xp: 1800 },
      { lvl: 85, title: 'Chosen Partner',       desc: 'A relationship you consciously chose.',                      xp: 3500 },
    ],
    cooking: [
      { lvl: 1,  title: 'Cook One Meal',        desc: 'Cook a meal from scratch.',                                  xp: 40 },
      { lvl: 3,  title: 'Three Dishes',         desc: 'Cook 3 different meals this week.',                           xp: 100 },
      { lvl: 6,  title: 'Signature Dish',       desc: 'Master one dish you can make blind.',                        xp: 200 },
      { lvl: 12, title: 'Five Recipes',         desc: 'Have 5 solid recipes in your pocket.',                       xp: 350 },
      { lvl: 20, title: 'Meal Prep',            desc: 'Prep a full week of meals in advance.',                      xp: 500 },
      { lvl: 35, title: 'Dinner Host',          desc: 'Cook a 3-course meal for guests.',                           xp: 900 },
      { lvl: 55, title: 'Twenty Recipes',       desc: 'Master 20 distinct recipes.',                                xp: 1600 },
      { lvl: 80, title: 'Home Chef',            desc: 'Cook restaurant-level food at home.',                        xp: 3000 },
    ],
    social: [
      { lvl: 1,  title: 'Reach Out',            desc: 'Message a friend you havent seen in a while.',               xp: 40 },
      { lvl: 3,  title: 'Make a Plan',          desc: 'Set up a hangout with someone.',                             xp: 90 },
      { lvl: 7,  title: 'Host Night',           desc: 'Organise a hangout for 3+ friends.',                         xp: 250 },
      { lvl: 15, title: 'New Friend',           desc: 'Turn an acquaintance into a friend.',                        xp: 400 },
      { lvl: 30, title: 'Wide Circle',          desc: 'Maintain 5 close friendships actively.',                     xp: 800 },
      { lvl: 50, title: 'The Connector',        desc: 'Introduce two people who become friends.',                   xp: 1400 },
      { lvl: 75, title: 'Community',            desc: 'Build or lead a group / community.',                         xp: 3000 },
    ],
    planning: [
      { lvl: 1,  title: 'Plan Tomorrow',        desc: 'Write tomorrows plan tonight.',                              xp: 40 },
      { lvl: 3,  title: 'Plan the Week',        desc: 'Map out a full week ahead.',                                 xp: 100 },
      { lvl: 7,  title: 'Weekly Review',        desc: 'Do a full weekly planning session.',                         xp: 250 },
      { lvl: 15, title: 'Time-Block a Day',     desc: 'Run one day fully time-blocked.',                            xp: 400 },
      { lvl: 25, title: 'Quarter Vision',       desc: 'Set and write 90-day goals.',                                xp: 700 },
      { lvl: 45, title: 'Run on the System',    desc: 'Use your own system for a month straight.',                  xp: 1200 },
      { lvl: 70, title: 'Life OS',              desc: 'Run your whole life from your system for a quarter.',        xp: 2800 },
    ],

    // ───────────── KNOWLEDGE ─────────────
    languages: [
      { lvl: 1,  title: 'First Words',          desc: 'Learn 20 words in a new language.',                          xp: 60 },
      { lvl: 3,  title: 'Hundred Words',        desc: 'Know 100 words.',                                            xp: 150 },
      { lvl: 6,  title: 'First Sentences',      desc: 'Form 5 correct sentences.',                                  xp: 250 },
      { lvl: 12, title: 'Small Talk',           desc: 'Hold a 2-minute basic conversation.',                        xp: 400 },
      { lvl: 20, title: 'Order & Ask',          desc: 'Get through a day abroad in the language.',                  xp: 700 },
      { lvl: 35, title: 'Read a Page',          desc: 'Read a full page and understand it.',                        xp: 1000 },
      { lvl: 50, title: 'Watch Without Subs',   desc: 'Watch a film with no subtitles and follow it.',              xp: 1600 },
      { lvl: 70, title: 'Think in It',          desc: 'Catch yourself thinking in the language.',                   xp: 2800 },
      { lvl: 90, title: 'Fluent Debate',        desc: 'Hold a 30-min deep conversation fluently.',                  xp: 5000 },
    ],
    piano: [
      { lvl: 1,  title: 'First Notes',          desc: 'Play a simple melody with both hands.',                      xp: 60 },
      { lvl: 3,  title: 'Read the Staff',       desc: 'Sight-read a simple bar of music.',                          xp: 120 },
      { lvl: 6,  title: 'Both Hands',           desc: 'Play hands-together for a full passage.',                    xp: 250 },
      { lvl: 12, title: 'First Song',           desc: 'Play one full song from memory.',                            xp: 450 },
      { lvl: 20, title: 'Three Songs',          desc: 'Build a 3-song repertoire.',                                 xp: 700 },
      { lvl: 35, title: 'Five Songs',           desc: 'Build a 5-song repertoire.',                                 xp: 1100 },
      { lvl: 55, title: 'Perform Live',         desc: 'Play for an audience, however small.',                       xp: 2000 },
      { lvl: 80, title: 'Improvise',            desc: 'Improvise freely over a chord progression.',                 xp: 3500 },
    ],
    learning: [
      { lvl: 1,  title: 'Start a Course',       desc: 'Begin any structured online course.',                        xp: 40 },
      { lvl: 5,  title: 'First Certificate',    desc: 'Complete one course fully.',                                 xp: 250 },
      { lvl: 12, title: 'Apply It',             desc: 'Use something you learned in real life.',                    xp: 400 },
      { lvl: 25, title: 'Stack Three',          desc: 'Complete 3 courses.',                                        xp: 800 },
      { lvl: 45, title: 'Deep Skill',           desc: 'Go deep enough to teach someone else.',                      xp: 1500 },
      { lvl: 70, title: 'Master a Domain',      desc: 'Reach real competence in a field.',                          xp: 3000 },
    ],

    // ───────────── CORE / NEW SKILLS ─────────────
    whistling: [
      { lvl: 1,  title: 'Make a Sound',         desc: 'Produce any clear note with fingers in your mouth.',         xp: 60 },
      { lvl: 2,  title: 'Find the Position',    desc: 'Find the finger + tongue position that works.',              xp: 70 },
      { lvl: 3,  title: 'Repeat It',            desc: 'Whistle on purpose 3 times in a row.',                       xp: 90 },
      { lvl: 5,  title: 'Loud & Clear',         desc: 'Whistle loud enough to turn heads across a room.',           xp: 200 },
      { lvl: 8,  title: 'Either Hand',          desc: 'Whistle with either hand / two-finger method.',              xp: 250 },
      { lvl: 15, title: 'On Command',           desc: 'Whistle reliably 9 out of 10 tries.',                        xp: 400 },
      { lvl: 25, title: 'Two-Tone',             desc: 'Whistle two distinct pitches on demand.',                    xp: 700 },
      { lvl: 40, title: 'Call the Dog',         desc: 'Whistle a tune someone can recognise.',                      xp: 1200 },
      { lvl: 60, title: 'Across the Park',      desc: 'A whistle that carries 100m.',                               xp: 2000 },
      { lvl: 85, title: 'Whistle Anything',     desc: 'Whistle melodies cleanly at will.',                          xp: 3500 },
    ],
    dancing: [
      { lvl: 1,  title: 'Find the Beat',        desc: 'Move on-beat to a full song.',                               xp: 60 },
      { lvl: 2,  title: 'Loosen Up',            desc: 'Dance alone in your room without judging it.',               xp: 70 },
      { lvl: 3,  title: 'One Basic Step',       desc: 'Learn one clean basic step.',                                xp: 90 },
      { lvl: 5,  title: 'One Routine',          desc: 'Learn a short choreographed sequence.',                      xp: 200 },
      { lvl: 8,  title: 'Two Songs',            desc: 'Dance through 2 full songs comfortably.',                    xp: 250 },
      { lvl: 15, title: 'Floor Confidence',     desc: 'Dance at a party fully sober and unbothered.',               xp: 400 },
      { lvl: 25, title: 'Lead the Group',       desc: 'Be the first one on the dance floor.',                       xp: 700 },
      { lvl: 35, title: 'Partner Up',           desc: 'Lead or follow a partner dance for one song.',               xp: 1000 },
      { lvl: 55, title: 'Own the Floor',        desc: 'Freestyle for a full song and enjoy it.',                    xp: 1800 },
      { lvl: 80, title: 'Performer',            desc: 'Dance in front of a crowd on purpose.',                      xp: 3500 },
    ],
  };

  window.RPG_QUESTS = QUESTS;

  // Storage of completed quests: { "skill:lvl": true }
  const QC_KEY = 'rpg_quests_done_v1';
  window.getQuestsDone = function () {
    try { return JSON.parse(localStorage.getItem(QC_KEY)) || {}; } catch (e) { return {}; }
  };
  window.setQuestDone = function (skill, lvl, done) {
    const all = window.getQuestsDone();
    const k = skill + ':' + lvl;
    if (done) all[k] = true; else delete all[k];
    try { localStorage.setItem(QC_KEY, JSON.stringify(all)); } catch (e) {}
    return all;
  };
})();
